### ISSUE TITLE
"Before hook" and "After hook" link are broken on the State page

### ISSUE THREAD

**Issue by Flaburgan** [cucumber/docs#107]
See https://cucumber.io/docs/reference/state

I don't know how to set a before hook, I'd like to read that page.

**Comment by mlvandijk** [comment]
@Flaburgan have a look here: https://cucumber.netlify.com/hooks/
Source: https://github.com/cucumber/docs.cucumber.io/blob/master/content/hooks.md

**Comment by mlvandijk** [comment]
Also, please note that this project is not the source for the current website (cucumber.io). It's intended to replace the docs on the current website.

**Comment by mlvandijk** [comment]
@Flaburgan Hoping this answered your question, I'm closing this issue.
