### ISSUE TITLE
Possible H1 H2 issue in in-page TOC

### ISSUE THREAD

**Issue by plaindocs** [cucumber/docs#108]
Might be related to this.

https://github.com/gohugoio/hugo/issues/1778

We use `#` on in page headers, which render as H1. (which should probably be rendered as H2 anyway), and the in-page toc seems to think `#` and `##` are of equal importance.

**Comment by mlvandijk** [comment]
Also, level 3 and 4 are added to TOC (if they're outside a language block), which I don't think they should be?
And it might be nice to have a difference between levels of headings visible in the TOC?

**Comment by plaindocs** [comment]
Fixed in 9e2f8b468
