### ISSUE TITLE
[PR #114] Add javascript example "Feature-coupled step definitions (anti-pattern)"

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#113]
There's one example missing for javascript in `anti-patterns.md`.
Java and Ruby examples for same are provided.
Missing example is marked "TODO" in the file.

**Comment by xtrasimplicity** [comment]
`anti-patterns.md` doesn't exist anymore. Are you referring to the section under `best-practices.md`?
https://github.com/cucumber/docs.cucumber.io/pull/77/files#diff-4a8d0ea6f2837fa485124e7c637a80af
 https://github.com/cucumber/docs.cucumber.io/pull/77/files#diff-3dce5767c9e094a30439b02976597ca4

**Comment by mlvandijk** [comment]
Hi @xtrasimplicity - thanks for pointing that out. I was working on a different branch when I wrote this issue. Yes, I mean an example in the [`best-practices.md`](https://github.com/cucumber/docs.cucumber.io/blob/master/content/best-practices.md) for the "Feature-coupled step definitions (anti-pattern)". I'll update the title.

**Comment by mlvandijk** [comment]
Background info: We're still working on the structure of the docs / navbar, see here: https://github.com/cucumber/docs.cucumber.io/pull/109 - where we may split `best-practices` again.

**Comment by xtrasimplicity** [comment]
Brilliant, thanks for clearing that up. I'll take a look at this when I get a chance. :)

**Comment by mlvandijk** [comment]
That would be great, thnx! :)
