### ISSUE TITLE
Find orphaned documents (automatically) and decide what to do with them

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#117]
Nice to have: find them automatically

**Comment by mlvandijk** [comment]
Some docs we've worked on (like assertions and mocking-and-stubbing) can go under "Guides"

**Comment by xtrasimplicity** [comment]
I wonder whether we could incorporate the [HTMLProofer ruby gem](https://github.com/gjtorikian/html-proofer) into the build pipeline, or use [something built for Hugo](https://discourse.gohugo.io/t/link-checker-for-go-hugo/2202/7)?

**Comment by aslakhellesoy** [comment]
As of 93c8dfa orphaned pages are printed at the end of `make htmlproofer`. The presence of orphans doesn't fail the build - it just prints them. There are currently 45 orphans. For each one of the orphan pages we should do one of the following:

* Move its content to an existing (linked) file
* Add a link in the nav
* Remove the page altogether

**Comment by mlvandijk** [comment]
Nice! I might move all the orphans to a separate folder then, so we know which documents we *need* to review now (as they're linked to) and which we can leave until later

**Comment by mlvandijk** [comment]
Yes, completely agree with those suggestions. In the mean time I might park the ones I'm unsure about in a separate folder.

**Comment by mlvandijk** [comment]
=== Orphaned pages ===
12:26:19 AM: public/wiki/cucumber-backgrounder/index.html
12:26:19 AM: public/wiki/autotest-integration/index.html
12:26:19 AM: public/wiki/a-whole-new-world/index.html
12:26:19 AM: public/highlight/index.html
12:26:19 AM: public/architecture/execution/index.html
12:26:19 AM: public/cucumber/environment-variables/index.html
12:26:19 AM: public/cucumber/cucumber.yml/index.html
12:26:19 AM: public/cucumber/checking-assertions/index.html
12:26:19 AM: public/cucumber/step-argument-transforms/index.html
12:26:19 AM: public/cucumber/wire-protocol/index.html
12:26:19 AM: public/admin/index.html
12:26:19 AM: public/tdd-introduction/index.html => merge with BDD (TODO)
12:26:19 AM: public/voting/index.html => Leave for later
12:26:19 AM: public/implementations/javascript/index.html => merge somewhere?
12:26:19 AM: public/implementations/jvm/java-di/index.html => **there is a link to this from the java tutorial!**
12:26:19 AM: public/implementations/jvm/index.html => merge this somewhere?
12:26:19 AM: public/implementations/cpp/index.html
12:26:19 AM: public/implementations/rust/index.html
12:26:19 AM: public/implementations/lua/index.html
12:26:19 AM: public/implementations/perl/index.html
12:26:19 AM: public/implementations/ruby/browsers-and-transactions/index.html
12:26:19 AM: public/implementations/ruby/custom-formatters/index.html
12:26:19 AM: public/implementations/ruby/sinatra/index.html
12:26:19 AM: public/implementations/ruby/ruby-on-rails/index.html
12:26:19 AM: public/implementations/ruby/console-colours/index.html
12:26:19 AM: public/implementations/ruby/ruby/index.html
12:26:19 AM: public/implementations/ruby/debugging/index.html
12:26:19 AM: public/implementations/ruby/calling-steps-from-step-definitions/index.html
12:26:19 AM: public/implementations/ruby/fixtures/index.html
12:26:19 AM: public/implementations/ruby/rake/index.html
12:26:19 AM: public/implementations/ruby/minitest/index.html
12:26:19 AM: public/implementations/cucumberish/index.html
12:26:19 AM: public/implementations/tcl/index.html
12:26:19 AM: public/implementations/godog/index.html
12:26:19 AM: public/implementations/dotnet-specflow/index.html
12:26:19 AM: public/implementations/python/index.html
12:26:19 AM: public/implementations/php/index.html

**Comment by plaindocs** [comment]
If I recall correctly, **most** of the implementation pages are just links to GitHub projects? So can easily be consolidated into a single page.

**Comment by mlvandijk** [comment]
@plaindocs true, but then we'd need to find a place for that page 
For now, we discussed to focus on the most used implementations, so imho we could park the others before go live

**Comment by mlvandijk** [comment]
@aslakhellesoy I think we might need to reconfigure a little bit. Some of the docs listed are linked to from other pages, for instance: 
https://cucumber.netlify.com/cucumber/state/ 
links to public/implementations/jvm/java-di/index.html

**Comment by mlvandijk** [comment]
See also: #25

**Comment by aslakhellesoy** [comment]
>  Some of the docs listed are linked to from other pages

@plaindocs and I had a chat about this, and we agreed on the principle that *all internal pages should be reachable from the nav*. Otherwise it might be too hard to find stuff.

To avoid an explosion of links from the front page, this means some pages will have to be quite long, but I think that's fine, as long as we have a good TOC for them.

**Comment by mlvandijk** [comment]
Yeah, that sound good! I can work on it this evening.

**Comment by plaindocs** [comment]
I think we can add Implementations to the `Cucumber` menu. And then put all or most of that content in a single page.

**Comment by mlvandijk** [comment]
@plaindocs will do. ~~Also want to add "Checking assertions" to Guides~~ (DONE)

**Comment by plaindocs** [comment]
~Working on the implementations over in #120~

**Comment by mlvandijk** [comment]
~~Merged TDD into BDD~~ (DONE)

**Comment by mlvandijk** [comment]
Updated list:
7:45:24 AM: === Orphaned pages ===
7:45:24 AM: public/implementations/php/index.html
7:45:24 AM: public/implementations/jvm/index.html
7:45:24 AM: public/implementations/ruby/sinatra/index.html
7:45:24 AM: public/implementations/ruby/debugging/index.html
7:45:24 AM: public/implementations/ruby/console-colours/index.html
7:45:24 AM: public/implementations/ruby/fixtures/index.html
7:45:24 AM: public/implementations/ruby/rake/index.html
7:45:24 AM: public/implementations/ruby/calling-steps-from-step-definitions/index.html
7:45:24 AM: public/implementations/ruby/ruby/index.html
7:45:24 AM: public/implementations/ruby/ruby-on-rails/index.html
7:45:24 AM: public/implementations/ruby/minitest/index.html
7:45:24 AM: public/implementations/ruby/custom-formatters/index.html
7:45:24 AM: public/implementations/ruby/browsers-and-transactions/index.html
7:45:24 AM: public/highlight/index.html
7:45:24 AM: public/cucumber/build-tools/index.html
7:45:24 AM: public/cucumber/cucumber.yml/index.html
7:45:24 AM: public/cucumber/wire-protocol/index.html
7:45:24 AM: public/cucumber/step-argument-transforms/index.html
7:45:24 AM: public/cucumber/environment-variables/index.html
7:45:24 AM: public/cucumber/editors/index.html
7:45:24 AM: public/architecture/execution/index.html
7:45:24 AM: public/admin/index.html
7:45:24 AM: public/wiki/autotest-integration/index.html
7:45:24 AM: public/wiki/a-whole-new-world/index.html
7:45:24 AM: public/wiki/cucumber-backgrounder/index.html
7:45:24 AM: public/voting/index.html
7:45:24 AM: public/step-reuse/index.html

**Comment by mlvandijk** [comment]
@aslakhellesoy Where should `build tools` and `editors` go?

`cucumber.yml` and `environment-variables` could be merged into `cucumber.md`? (under configuration?) - I don't know enough about either

**Comment by mlvandijk** [comment]
Since `calling-steps-from-step-definitions` is considered an anti-pattern (and that's the only place it's linked to), should we delete it? It also contains information on "Multiline step arguments" that may or may not be relevant elsewhere. Since it's a Ruby feature, I'll leave it for others to decide.

**Comment by mlvandijk** [comment]
`/implementations/ruby/custom-formatters/` is linked to from `cucumber.md` - Also a Ruby feature. Should it be merged or deleted?

**Comment by mlvandijk** [comment]
`wiki/autotest`  is linked to from `content/about/related-tools.md` - Also a Ruby feature. Should it be merged or deleted? (Note: this is the only doc listed in #25 that is currently linked to)

**Comment by aslakhellesoy** [comment]
> Where should build tools and editors go?

Let’s create a `tools.md` page with a h1 for each category of tools (build tools, editors)

**Comment by mlvandijk** [comment]
Sounds good! ~~(working on it)~~ DONE

**Comment by mlvandijk** [comment]
@aslakhellesoy What is `highlight.md` for and do we still need it?

**Comment by mlvandijk** [comment]
@aslakhellesoy What is your intention with `step-reuse.md`?

**Comment by mlvandijk** [comment]
I've moved all of the unlinked orphans (i.e. docs that are not linked to from other docs) to folder `_orphans`; imho these docs do not need to be reviewed before GoLive.

**Comment by plaindocs** [comment]
`highlight.md` is probably just a test for tweaking the code highlighting - can either be deleted or moved to the theme dir.

**Comment by mlvandijk** [comment]
If not needed anymore, let's delete?

**Comment by plaindocs** [comment]
I think so.

**Comment by mlvandijk** [comment]
**Updated list of orphans**

Notes: 
* I've marked the docs that are linked to from pages that are currently active (i.e. accessible from the menu) => these should be reviewed before GoLive
* Everything in "_orphans/" is not linked to from other pages.
* Everything else does link to each other internally (so I didn't move them to "_orphans" because that would break the links), but not from active pages.

11:27:11 AM: === Orphaned pages ===
11:27:11 AM: public/cucumber/environment-variables/index.html
11:27:11 AM: public/cucumber/cucumber.yml/index.html
11:27:11 AM: public/wiki/autotest-integration/index.html ~~**=> linked to from `related-tools.md`**~~ **UPDATE: Removed from `related tools`** 
11:27:11 AM: public/wiki/a-whole-new-world/index.html
11:27:11 AM: public/admin/index.html **=> What's this for?**
11:27:11 AM: public/_orphans/architecture/execution/index.html
11:27:11 AM: public/_orphans/implementations-php/index.html
11:27:11 AM: public/_orphans/voting/index.html
11:27:11 AM: public/_orphans/cucumber-backgrounder/index.html
11:27:11 AM: public/_orphans/wire-protocol/index.html
11:27:11 AM: public/_orphans/ruby/fixtures/index.html
11:27:12 AM: public/_orphans/ruby/minitest/index.html
11:27:12 AM: public/_orphans/ruby/console-colours/index.html
11:27:12 AM: public/_orphans/step-argument-transforms/index.html
11:27:12 AM: public/_orphans/step-reuse/index.html
11:27:12 AM: public/implementations/ruby/custom-formatters/index.html ~~**=> linked to from `cucumber.md`**~~ **UPDATE: Unlinked**
~~11:27:12 AM: public/implementations/ruby/sinatra/index.html **=> linked to from `related-tools.md`**~~ **REMOVED (project was archived by owner)**
11:27:12 AM: public/implementations/ruby/ruby-on-rails/index.html ~~**=> linked to from `tools.md` and `related-tools.md`**~~ **UPDATE: Removed links. Content should be merged?**
11:27:12 AM: public/implementations/ruby/debugging/index.html
11:27:12 AM: public/implementations/ruby/calling-steps-from-step-definitions/index.html ~~**=> linked to from `anti-patters.md`**~~ **UPDATE: Unlinked**
11:27:12 AM: public/implementations/ruby/browsers-and-transactions/index.html
11:27:12 AM: public/implementations/ruby/rake/index.html
~~11:27:12 AM: public/highlight/index.html **=> if not needed, let's delete?**~~ DONE

**Comment by aslakhellesoy** [comment]
highlight.md is indeed a test page that should be deleted

**Comment by mlvandijk** [comment]
Done ;)

**Comment by mlvandijk** [comment]
If I understand correctly, `autotest` is part of zentest, which was last updated almost 2 years ago on [Jun 13, 2016](https://github.com/seattlerb/zentest) - Is it still used, or can it be deleted? In the mean time, I've removed zentest/autotest from `related-tools`, but cannot move it to "_orphans" as `cucumber.yml` also links to it.

**Comment by mlvandijk** [comment]
[Sinatra](https://github.com/bernd/cucumber-sinatra) has been archived by owner, so I removed the link from `related-tools` as well as `implementations/ruby/sinatra.md` in [this commit](https://github.com/cucumber/docs.cucumber.io/commit/320de9472b3acc4e1cf367ff307c9f5669a0a241)

**Comment by mlvandijk** [comment]
Maybe `related-tools.md` could use a review/update to see if it contains other tools that might be outdated?

**Comment by mlvandijk** [comment]
Closed, moved to #130
