### ISSUE TITLE
Improve in page TOC

### ISSUE THREAD

**Issue by plaindocs** [cucumber/docs#118]
https://abouolia.github.io/sticky-sidebar/ maybe?

**Comment by mlvandijk** [comment]
Discussed with @aslakhellesoy today:
* TOC should distinguish between level of headers. (Example we looked at: http://kotlinlang.org/docs/tutorials/ - folding in and out is not necessary, also longer pages are fine but should have "jump to" TOC)
* TOC should not be "lost" when scrolling down, especially if we're making longer pages (i.e. Cucumber reference)
* Very short pages may not need TOC (e.g. install page?); possibly be able to turn off/on TOC for a page in the frontmatter

Sidenote: TOC doesn't work when inside of language block

**Comment by plaindocs** [comment]
Sounds good. I'm looking at implementing stickiness on the menu.

I think the solution to the language blocks is to remove all titles from them. @aslakhellesoy is writing a linter for that, and we can then fix it. 

I'll look into multi level TOC, not sure it works out of the box.

**Comment by mlvandijk** [comment]
If by removing titles from language blocks you mean make sure they're outside of the language block, then yeah! 
Note: There might be titles that are only relevant inside a language block though? I.e. Maven for Java, npm for Javascript, bundler for Ruby. Sections should have a high level title outside the language block, i.e. build tools or something, but language specifics inside the block.

**Comment by plaindocs** [comment]
Yeah, making sure they're outside. 

We can probably write around most cases, although the ones you mention might be tricky

**Comment by mlvandijk** [comment]
Make them bold instead of headers?

**Comment by mlvandijk** [comment]
Also, see #108 (and maybe merge these issues?)

**Comment by plaindocs** [comment]
Fixed in 9e2f8b468
