### ISSUE TITLE
Fix Cucumber logo ~~+ GitHub logo~~ in landing page

### ISSUE THREAD

**Issue by plaindocs** [cucumber/docs#121]

**Comment by mlvandijk** [comment]
The Cucumber logo is "squashed".
~~The GitHub logo is not properly aligned (should be centered above the text.~~ Fixed in #138

**Comment by aslakhellesoy** [comment]
It’s a regression I introduced when I made the TOC scrollable

**Comment by mlvandijk** [comment]
I'd like for the logo to retain it's height:width ratio, but have no idea how to do that...

**Comment by plaindocs** [comment]
Great work @mlvandijk !
