### ISSUE TITLE
Add Anchor markers to Headings

### ISSUE THREAD

**Issue by plaindocs** [cucumber/docs#123]
Hugo already generates the id so we need to add the link

https://discourse.gohugo.io/t/adding-anchor-next-to-headers/1726/9
or
https://stackoverflow.com/questions/42213736/hugo-automatically-link-headers

**Comment by TomerPacific** [comment]
Hi @plaindocs ,
I would like to help. Is there a preferred way you would like this to be solved?
Also, it might take me a while since I am not familiar with Hugo.

**Comment by plaindocs** [comment]
Hey @TomerPacific , welcome, and thanks for helping out.

As mentioned above, Hugo automatically generates the ID from the heading text, so we just need to add an on mouse-over behaviour to show a '`#`' that contains that link.

We'd probably prefer to do this within the templating language when generating the site, rather than with Javascript.  In the discourse link above there is mention of a modifer to `{{ .Content }}` you might try.

Try applying that in `single-content.html` partial and `index.html` layout. 

Let me know how you get on. :-)

**Comment by TomerPacific** [comment]
@plaindocs ,
thanks for the detailed reply.
I'll take a look at it and update you on how I progress.

26.10.18 Update
I have looked at the discourse link above and have added code to single-content.html and index.html. I am currently in the process of creating a local development environment to see if my changes work.

2.11.18 Update
@plaindocs , When trying to run the website locally through docker, I get the following message:

> Error response from daemon : OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"\\r\": executable file not foun in $PATH": unknown

Do you have any idea what seems to be the problem? Tried looking online for help, but found nothing relevant.

**Comment by plaindocs** [comment]
Hey @TomerPacific 

Can you run the Docker command `./docker_shell.sh` on master branch before applying your changes?

**Comment by plaindocs** [comment]
Also please comment below, instead of editing, so I get a notification.

**Comment by TomerPacific** [comment]
@plaindocs ,
I figured as much, since I didn't see you commenting.
I don't know if I'll be able to run docker on master since it does not run locally on my machine. I'll give it a try and update here (with a new comment)

**Comment by TomerPacific** [comment]
@plaindocs,
tried running the command after switching to master branch, but I am still getting the same error. I have to make it clear that I am running things on a **Windows machine with Windows7 64bit**.

**Comment by plaindocs** [comment]
Hmmm, then I'm not really sure.

Maybe @mlvandijk has tips on running on Windows?

Or you could push your work up to a branch and use the Preview for the PR?

**Comment by mlvandijk** [comment]
Sorry no tips on running docker on windows... the other option is to push to a branch, create a PR and use preview (show all checks -> details), like @plaindocs suggested. Please mark the PR as WIP while you are working on it so we know not to merge

**Comment by TomerPacific** [comment]
@plaindocs , @mlvandijk ,
I have opened a [PR](https://github.com/cucumber/docs.cucumber.io/pull/258)

**Comment by TomerPacific** [comment]
@mlvandijk , consider closing this issue.

**Comment by mlvandijk** [comment]
Thanks @TomerPacific and @plaindocs
