### ISSUE TITLE
Explain the history of BDD and Cucumber

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/docs#133]
Some good links here: https://cucumberbdd.slack.com/archives/C60TKS3SL/p1517802145000082

I’ll assign this to myself

**Comment by mlvandijk** [comment]
Links (from Slack): 

https://en.wikipedia.org/wiki/Behavior-driven_development#History

https://en.wikipedia.org/wiki/Behavior-driven_development

https://lizkeogh.com/2011/06/27/atdd-vs-bdd-and-a-potted-history-of-some-related-stuff/

http://blog.davidchelimsky.net/blog/2007/10/21/story-runner-in-plain-english/ 

https://www.quora.com/Why-is-the-Cucumber-tool-for-BDD-named-as-such

**Comment by mlvandijk** [comment]
https://books.google.nl/books?id=k6isDwAAQBAJ&pg=PA155&lpg=PA155&dq=liz+keogh&source=bl&ots=MZO0d4eBnm&sig=ACfU3U2qco1yNze0h73eOtmjyKqwOBT3Ow&hl=en&sa=X&ved=2ahUKEwjnldXX-d_mAhWJalAKHePdDXA4RhDoATAJegQIChAB#v=onepage&q=liz%20keogh&f=false

**Comment by lisacrispin** [comment]
I'm going to take a stab at this.

**Comment by lisacrispin** [comment]
I'm curious what the purpose of this is. Just general interest? Or is there a particular reason we want people to know the history?

**Comment by lisacrispin** [comment]
> https://books.google.nl/books?id=k6isDwAAQBAJ&pg=PA155&lpg=PA155&dq=liz+keogh&source=bl&ots=MZO0d4eBnm&sig=ACfU3U2qco1yNze0h73eOtmjyKqwOBT3Ow&hl=en&sa=X&ved=2ahUKEwjnldXX-d_mAhWJalAKHePdDXA4RhDoATAJegQIChAB#v=onepage&q=liz%20keogh&f=false

I'm not sure what that book was meant to be, the link doesn't work.

**Comment by lisacrispin** [comment]
Another useful link: http://edgibbs.com/2007/12/02/jbehave-and-rspec-history/
