### ISSUE TITLE
Close down / archive / redirect old doc sources

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#144]
Any relevant information from wiki-pages should be added to the docs. See below for a list of wiki pages. Note that a lot of content is marked "removed" because it was either too little information and/or very outdated. If the topics are considered relevant, please provide a PR with sufficient and up-to-date information.

**Comment by mattwynne** [comment]
I've set up redirects from the old sites (via Cloudflare page rules):

- `docs.cucumber.io/docs/*` (the old gitbook site's URLs) now redirects to the `docs.cucumber.io` homepage
- `cucumber.io/docs/*` redirects to the `docs.cucumber.io` homepage

I didn't add any redirects for specific URLs because pragmatism.  I don't like breaking links and at the same time I don't know how important it is to keep them. If there are any specific URLs people want redirected please let me know.

The wiki has been closed for edit, and @aslakhellesoy is going through the pages to add redirects (where applicable) to the new pages.

**Comment by mlvandijk** [comment]
See also #42 (possible duplicate)

**Comment by mlvandijk** [comment]
TO BE REMOVED:
- [ ] https://github.com/cucumber/cucumber/wiki/Autotest-Integration (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/Console-Colours (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/Cucumber-Backgrounder  (content was moved to relevant sections and a lot of it was deleted)
- [ ] https://github.com/cucumber/cucumber/wiki/Cucumber-Feature (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/Fixtures (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/FunFX-and-Flex (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/IronRuby-and-.NET (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/IronRuby-and-Mono (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/Patterns (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/Merb (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/RDoc (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/Setting-up-Selenium (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/Setting-up-Steam (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/Sinatra (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/Snailgun-and-Cucumber (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/Step-Argument-Transforms
- [ ] https://github.com/cucumber/cucumber/wiki/subdomain_fu-and-incorrect-redirection-to-%22-body-You-are-being-redirected--body-%22-page (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/Troubleshooting (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/Using-AE (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/Using-MiniTest (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/Using-RCov-with-Cucumber-and-Rails (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/Watircraft (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/watircuke (removed)
- [ ] https://github.com/cucumber/cucumber/wiki/Wire-Protocol (removed)

DONE: 
- [x] https://github.com/cucumber/cucumber/wiki/Custom-Formatters
- [x] https://github.com/cucumber/cucumber/wiki/Debugging
- [x] https://github.com/cucumber/cucumber/wiki/Environment-Variables
- [x] https://github.com/cucumber/cucumber/wiki/cucumber.yml
- [x] https://github.com/cucumber/cucumber/wiki/Step-Organisation => **Note: page was removed from wiki**
- [x] https://github.com/cucumber/cucumber/wiki/Translations (DONE: info added in PR #281)
TODO:
- [ ] https://github.com/cucumber/cucumber/wiki/Upgrading (DONE, Page added in #312)

**Comment by mlvandijk** [comment]
Note: https://github.com/cucumber/cucumber-js/issues/1098 mentions a dead link to https://docs.cucumber.io/event-protocol/ - Any way to find out what used to be there?

**Comment by mlvandijk** [comment]
Added the following to the top of every page listed above:
```
[The documentation has moved](https://docs.cucumber.io/).

Please do not make further edits to this Wiki.

**Note:** If this page contains information that is useful to you, 
please consider adding it to the docs project on GitHub.

===================================================================

```

@mattwynne I'd suggest removing the wiki in a few months (around April the docs site will have been up a full year).
If you like we can add a deadline to the top of the pages, stating when it will be removed?

**Comment by mattwynne** [comment]
I’m a fan of timeboxes, let’s do it.

**Comment by mlvandijk** [comment]
Excellent! What deadline should we use? (I.e. a date you'd be available to shut it off ;) I'll have time this week to update the pages with the deadline.

**Comment by mlvandijk** [comment]
Also, I figure some of the pages might be about outdated tools and could be deleted already? If so, please let me know! I'm not familiar with most of them, I'm afraid.

**Comment by mattwynne** [comment]
How about we do it at CukenFest? We can go through them and do a purge.

**Comment by mlvandijk** [comment]
Awesome!

**Comment by mlvandijk** [comment]
@mattwynne We forgot to do this at Cukenfest. Can we shut it down? Afaik most/all of the information on the remaining pages is outdated.

**Comment by mattwynne** [comment]
I would be supportive of us doing that @mlvandijk yeah. The docs site is really coming together now, and I think it's better just to signpost people to there.

Is the idea still to update the pages with a link to the new doc site, rather than actually turn off the wiki?

**Comment by mlvandijk** [comment]
Idk, that might be helpful. We should anyway remove all of the old/outdated content imho

**Comment by mlvandijk** [comment]
I think we can also just shut it down. It's been linking to the new docs for a while now.

**Comment by mlvandijk** [comment]
I would anyway like to close this issue somehow ;)

**Comment by mattwynne** [comment]
I turned off the wiki!

I'll let you have the satisfaction of closing the issue @mlvandijk!

**Comment by mlvandijk** [comment]
Better late than never

**Comment by mattwynne** [comment]
💥
