### ISSUE TITLE
Customize the 404 page

### ISSUE THREAD

**Issue by plaindocs** [cucumber/docs#148]
Current 404 is a blank page.
The only way to know that a link was not found, is that the title of the page contains 404.

**Comment by robzenn92** [comment]
This is just a start, do not take it seriously.. I just want to start discussing on it.. do we have some ideas on how we want it to be? 😃 I see that cucumber.io has [this](https://cucumber.io/404), do we need to be consistent with that? For example, I like [this one](https://s3.envato.com/files/134787808/screen2.jpg).

<img width="1437" alt="404_v0 1" src="https://user-images.githubusercontent.com/3225625/41444218-f9773c3e-7041-11e8-94b1-88b7c564ba9d.png">

**Comment by mlvandijk** [comment]
Hi @robzenn92 - Thanks for your input! Really happy to have someone on board who can pick up front end stuff. :)
My thoughts:
While in general, I'm in favor of consistency, I don't particularly like the 404 on the website. (sorry @mattwynne!). Providing a list of topics seems like a good idea, but makes the page harder to quickly understand. The docs have a landing page, with an overview of topics. Imho we should just link there.
So, I like your other ideas! Something simple, with a Cucumber in there, that clearly states the page could not be found and with the option to go back to the homepage (docs-home in this case; the landing page).
Also, it might be good to keep the [styleguide](https://github.com/cucumber-ltd/brand) in mind.

If you'd like to discuss further, please join us on Slack?

**Comment by robzenn92** [comment]
Yeah, I think that the GIF page is definitely a good start, but I also think that a more 'serious' 404 page is needed. Anyway.. yeah I'll take the time to join you on Slack to further discuss and share ideas about it.

**Comment by mlvandijk** [comment]
@robzenn92 Really liked your ideas, so feel free to just get started on something similar. (I cant design to save my life, so you'd be a big help!)

**Comment by robzenn92** [comment]
Mockups will be provided! 👍  just give me some more time! 😄

**Comment by mlvandijk** [comment]
Great! And ofcourse; it's volunteer work ;)

**Comment by mattwynne** [comment]
Thankyou @robzenn92!

**Comment by mlvandijk** [comment]
Stumbled upon this:https://www.creativebloq.com/web-design/best-404-pages-812505 (for inspiration)

**Comment by cowang** [comment]
So is the "Dill with it" page what we want? is this issue ready to close?

Pull request was #199.
The only question is whether everyone is satisfied with that. (Looks good to me.)

**Comment by luke-hill** [comment]
There is a custom 404 page. Lets close this now and see if anyone wants to land anything new.

**Comment by mlvandijk** [comment]
I'd prefer for it to be consistent with the website, but that might be part of a bigger story.

**Comment by mattwynne** [comment]
The one on the website is just squarespace's default, and could happily be changed. I like your design @robzenn92 (though I think we could lose the (R) on the cucumber logo).
