### ISSUE TITLE
Point to this repo for contributions to the documentation

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#15]
(As discussed on Slack between @aslakhellesoy and myself:)

# Summary
All docs updates should be in the new docs.cucumber.io repo

# Goal
Prevent duplicated / out of sync documentation, and/or rework to update documentation from other sources into this repo.

# Solution 
Add info to all individual sets of documentation (at least as mentioned in the README of this repo), placing a "do not update" warning somewhere, with an link pointing to this project for documentation updates.
Information should be placed where contributors are most likely to see that warning, starting with:
* Contributing.md file (s) in various repos
* Commit guidelines

# TODO:
Add text with a link to this repo to the following repos/documents:
> **Note:** Do not update documentation in *this* repo. We are busy adding old documentation to a new repository [docs.cucumber.io](https://github.com/cucumber/docs.cucumber.io) to replace the current documentation on cucumber.io.
Please make **ALL** contributions to the documentation [here](https://github.com/cucumber/docs.cucumber.io).

Text should be added to:
- ~~Contributing to Documentation: https://github.com/cucumber/cucumber/blob/master/docs/contributing-to-documentation.md~~ (DONE)
- ~~About this documentation: https://github.com/cucumber/cucumber/blob/master/docs/about-this-documentation.md~~ (Updated to point to docs.cucumber.io)

Point CONTRIBUTING.md's in various repos to "Contributing-to-documentation.md" in docs.cucumber.io:
- ~~Cucumber Community Contributing Guide 1.0: https://github.com/cucumber/cucumber/blob/master/CONTRIBUTING.md (?)~~ (DONE: Updated link)
- ~~Commit guidelines~~ (=Cucumber Community Contributing Guide 1.0)

Contributing.md file (s) in various repos:
* ~~2008 onwards: [Cucumber wiki (primarily Ruby)](https://github.com/cucumber/cucumber/wiki)
=> https://github.com/cucumber/cucumber/wiki/Contributing (?)~~ (Done: linked to new docs Contributing page)
* 2008 onwards: Misc README files for different implementations:
  * https://github.com/cucumber/cucumber-ruby
  * https://github.com/cucumber/cucumber-jvm
  * https://github.com/cucumber/cucumber-js
* ~~2015 onwards: [https://cucumber.io/docs](https://cucumber.io/docs)
  * Based on our own website app (Jekyll-like)
  * [source](https://github.com/cucumber/website/tree/master/apps/dynamic/views/docs)~~ (DONE: Already removed)
* 2016 onwards: [https://docs.cucumber.io/](https://docs.cucumber.io/)
  * Based on GitBook
  * [source](https://github.com/cucumber/cucumber)
  * ~~See [SUMMARY.md](https://github.com/cucumber/cucumber/blob/master/SUMMARY.md) for the outline~~ (DONE: Was removed)

**Comment by paoloambrosio** [comment]
That message is relevant only if someone is actively working on porting the documentation.

Given historical struggles to port documentation into a single repo, I suggest this workflow for big-size source repos:
 - do nothing till someone actually starts working on it :)
 - raise an issue X in "docs.cucumber.io" about the intent of porting docs from "cucumber-something"
 - raise an issue Y in "cucumber-something" referencing the one on "docs.cucumber.io"
 - add the aforementioned message to the "cucumber-something" repo (referencing Y)
 - loop
   - make additions to "docs.cucumber.io" (referencing X)
   - when a portion has been moved, remove it from "cucumber-something" (referencing Y)
 - when everything is done, close X, and remove "We are busy adding old documentation..." from "cucumber-something", closing Y

It might be overkill, so feel free not to consider this. I'm just worried that we are going to have yet another documentation repo on top of the existing ones, so I would give it a bit of structure.

**Comment by mlvandijk** [comment]
@paoloambrosio Great suggestion! That was my intention also by starting with pointing the repos that are being moved here.

**Comment by mlvandijk** [comment]
All done, except for consolidating documentation from specific implementations. For that I created a new issue: #188
