### ISSUE TITLE
tag expressions example - unreadable

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/docs#162]
The example [here](https://docs.cucumber.io/cucumber/api/#tag-expressions) of tag expressions with parenthesis is hard to read as the parenthesis are not visible (they are black on black)

**Comment by olleolleolle** [comment]
The example `(@smoke or @ui) and (not @slow)` has the black-on-black-background parentheses.

**Comment by mlvandijk** [comment]
Thanks for pointing this out @charlierudolph and for working on a fix @xtrasimplicity !

**Comment by xtrasimplicity** [comment]
https://github.com/cucumber/docs.cucumber.io/issues/163 has been merged! :)
