### ISSUE TITLE
Cucumber JVM docs issues with versions while using maven

### ISSUE THREAD

**Issue by naveenb29** [cucumber/docs#17]
I followed the docs and ran into an issue similar to this - 

https://stackoverflow.com/questions/25291480/cucumber-exception-java-lang-classnotfoundexception-cucumber-io-resourceloader

I needed to make 2 fixes add the `cucumber-core` to my dependencies and also increment the `cucumber-junit` version to `cucumber-java's` versions (2.0.X)

I would like to send a pull for this if the community thinks this is a valid concern for beginners.

**Comment by plaindocs** [comment]
Hi @naveenb29 

Thanks for looking into that. We're *heavily* refactoring the docs in https://github.com/cucumber/docs.cucumber.io/pull/3 so make sure you branch from `sw-reorg` before making the changes.  :-)

And for sure! Examples that don't work are no fun for anyone

**Comment by mlvandijk** [comment]
@naveenb29 Branch sw-reorg has just been merged to master; you can create a PR to master

**Comment by mlvandijk** [comment]
Fixed by PR #76
