### ISSUE TITLE
Team page

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/docs#173]
Such a vibrant open source community deserves a team page. Let's create one like https://zeit.co/about. Each contributor will be invited to edit their own markdown page and add their gravatar url in the front matter.

**Comment by robzenn92** [comment]
Sounds good! I could start working on it! Are we fine with a page like [https://zeit.co/about](https://zeit.co/about)? Shall we propose some other ideas/prototypes?

**Comment by mlvandijk** [comment]
Really like your enthousiasm, @robzenn92! :) 

A page like Zeit's seems fine to me. Imho we could use:
- avatar
- name / github username (preferably with link to github account?)
- twitter handle (optional)
- description

Btw, please join us on Slack (register for an account [here](https://cucumberbdd-slack-invite.herokuapp.com/), if needed) in the #docs channel ;)

**Comment by aslakhellesoy** [comment]
@robzenn92 that sounds great! Would be great to grab all the metadata from a JSON/YAML file if you can figure that out.

**Comment by aslakhellesoy** [comment]
Actually, better than a YAML/JSON file would be a `team` directory with `{githubuser}.md` files. We can then build a grid similar to https://docs.cucumber.io/installation/

**Comment by aslakhellesoy** [comment]
I started it over at https://github.com/cucumber/docs.cucumber.io/pull/191 - there was a little bit of Hugo/HTML hacking to do.

Please add your own page!

**Comment by mlvandijk** [comment]
@robzenn92 Now that @aslakhellesoy has beat you to it, we also need a nice 404 page (see #148), if you wanna give that a go?

**Comment by mlvandijk** [comment]
Team page was added in #191 - everyone can add their own page as desired ;)
