### ISSUE TITLE
Update bad link to Hexagonal Architecture

### ISSUE THREAD

**Issue by rlabok** [cucumber/docs#177]
The link for "hexagonal architecture" goes to a site that is not responding.  Is there a better location to redirect to?

> This architectural patterns is called ports and adapters pattern (or hexagonal architecture). It enables you to connect your scenarios and unit tests at a lower level, while the contract tests give you the confidence to do that.

`**ports and adapters pattern** (or [hexagonal architecture](http://a.cockburn.us/1807)`

**Comment by xtrasimplicity** [comment]
Thanks @rlabok. That link (when it works) takes you to Alistair Cockburn's blog post - he's the guy who came up with the term "Hexagonal architecture", so it's probably one of the best resources we could link to - - when the site is online, of course. :)

**Comment by xtrasimplicity** [comment]
Looks like we may need to find some new documentation, or recover it from Google cache and archive it?

https://mobile.twitter.com/totheralistair/status/1005865169090760704

**Comment by olleolleolle** [comment]
Current status: http://a.cockburn.us/1807 resolves to http://alistair.cockburn.us/Hexagonal+architecture - and it's a full rendering of the site. Seems OK, right now, at least.

**Comment by xtrasimplicity** [comment]
Thanks @olleolleolle - I checked a few minutes ago and this didn't resolve, so I'm glad it's working now.

Given Alistair's comments on Twitter, though, I wonder whether we should list a few different sources?

**Comment by olleolleolle** [comment]
@xtrasimplicity - I'm partial to Archive.org's Wayback Machine for things like this.

**Comment by mlvandijk** [comment]
@rlabok Thanks for filing an issue. Note that we use HTMLProofer to check for dead links (at deploy time), so if and when it truly dies, we should know and be able to replace the link. 
If anyone wants to replace with either a Wayback Machine link, that would be great.

**Comment by mlvandijk** [comment]
Fixed by #234
