### ISSUE TITLE
Suggestion: add a link to the cucumber.io homepage

### ISSUE THREAD

**Issue by robzenn92** [cucumber/docs#182]
Hi !
I see that on this site there is no link to the Cucumber's homepage (https://cucumber.io/).
Shall we add it? I was expecting it, in my opinion it is quite annoying not to have it.

Thanks,
Roberto

**Comment by aslakhellesoy** [comment]
Yes please! Any thoughts where you'd put it?

**Comment by robzenn92** [comment]
I would put it at least on the logo. I will create a PR with the change. Meanwhile, if anyone else has other advices on this, I can revise it till we are fine with that. Let me know.
