### ISSUE TITLE
Bug in polyglot page selection

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#195]
Sometimes when I switch between language tabs, they don't seem to keep up properly, resulting in my seeing a Ruby logo with the "Java" tab selected.

Steps to reproduce (updated):
1. Select "Java" (will show Java logo and text "Java" in dropdown, along with Java page content)
2. Select Ruby (will show Ruby logo and text "Ruby" in dropdown, along with Ruby page content)
3. Go to another page (i.e. via the menu)

**Actual result:**
Shows Ruby logo with "Java" and Ruby content.
<img width="187" alt="screen shot 2018-06-15 at 16 22 26" src="https://user-images.githubusercontent.com/20927578/41473098-9f95a9d6-70b8-11e8-881f-17fe67c44bcb.png">

**Expected result:**
Keep last selected option, so in this case that would be Ruby logo, option and content.

System:
* Mac OS
* Firefox 
(can provide additional details)

**Comment by aslakhellesoy** [comment]
Yeah I've seen it. I'll try to bring the tabs back.

**Comment by mlvandijk** [comment]
Updated the issue with more specific steps to reproduce

**Comment by mlvandijk** [comment]
Thnx @aslakhellesoy !
