### ISSUE TITLE
Debugging documentation out-of-date

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/docs#197]
_From @cameroncooke on April 27, 2018 16:28_

## Summary

The debugging documentation on the Wiki is out of date. The `debugging.rb` code does not work with `2.4.0`.

https://github.com/cucumber/cucumber/wiki/Debugging

On running the tests one or more exceptions are thrown from the `debugging.rb` code.

## Expected Behavior

I would expect that the debugging logic not to throw it's own exceptions and perform it's intended function.

## Current Behavior

The following exception is observed in the terminal when running tests.

```bash
 uninitialized constant Rails (NameError)
 ./features/support/debugging.rb:47:in `rescue in failed'
 ./features/support/debugging.rb:41:in `failed'
```

## Steps to Reproduce (for bugs)

1. Add the `debugging.rb` file to your project following the instructions found here: https://github.com/cucumber/cucumber/wiki/Debugging
2. Run the tests using `DEBUG=1` environmental variable

## Context & Motivation

I would like to be able to debug my test code. My main motivation for debugging was to be able to get a breakpoint using `pry` when an exception is thrown in one of my tests.

## Your Environment

* Version used: 2.4.0
* Operating System and version: macOS 10.13.4

_Copied from original issue: cucumber/cucumber#376_

**Comment by aslakhellesoy** [comment]
_From @mlvandijk on June 14, 2018 11:36_

Note that we have moved the documentation here: https://docs.cucumber.io/
You can find the source [here](https://github.com/cucumber/docs.cucumber.io), if anyone would like to add debugging information.

**Comment by olleolleolle** [comment]
I amended the wiki page (https://github.com/cucumber/cucumber/wiki/Debugging), so that there's something until a full documentation page has been added in docs.cucumber.io.

**Comment by mlvandijk** [comment]
Thanks @olleolleolle! Would you like to move the Debugging info to the docs?

**Comment by aslakhellesoy** [comment]
Yes - please don't add anything to the wiki anymore, it will soon be deleted.

**Comment by olleolleolle** [comment]
I'll be adding a Debugging square to the other Cucumber squares in this repo's documentation. It's my first `polyglot` article here.

**Comment by olleolleolle** [comment]
Alright, now I brought in that content into a proto-article.

**Comment by mlvandijk** [comment]
Thank you! We can collaborate on that and merge when sufficient. I think (hope!) Andrew might like to collaborate as well.

**Comment by olleolleolle** [comment]
#211 is the current article.

**Comment by mlvandijk** [comment]
Thanks for your help on this @olleolleolle and @luke-hill!
