### ISSUE TITLE
consider using https://github.com/lord/slate for the publishing platform

### ISSUE THREAD

**Issue by mattwynne** [cucumber/docs#2]
If it does multi-language support out of the box, that would save us having to build our own stuff.

Need to check things like:
- is there a user-friendly way to edit the docs for @RebekahLawrence to use
- does it do multi-language support the way stripe's API docs do?
- is there enough flexibility in the nav to have nested levels of docs?

Anything else I missed?

Can you own this and have a look into it @aslakhellesoy?

**Comment by aslakhellesoy** [comment]
I've already considered using it, and decided not to for the following reasons:

* The main (middle) column for prose is very narrow, not great for reading longer paragraphs of text (and illustrations)
* I find it hard to tweak themes
* No support for different content in the prose column

I believe I have addressed all of these concerns. Here is a demo:
https://cucumber.netlify.com/reference/step-definitions/

And the source code for that page:
https://github.com/cucumber/docs.cucumber.io/blob/master/content/reference/step-definitions.md

I find the combination [Hugo](https://gohugo.io) static site generator and [Bulma](http://bulma.io/) CSS framework very easy to work with and I prefer to go with that.

**Comment by aslakhellesoy** [comment]
Another drawback of Slate is its single page nature. Just having a single document for all the docs sounds messy.
