### ISSUE TITLE
Contributing to documentation page is not rendered completely

### ISSUE THREAD

**Issue by akshaykamath** [cucumber/docs#200]
Hi,
I was just browsing through the contribution process and saw that the page is not rendered completely after the "Language Specific source code and paragraphs" section:
https://docs.cucumber.io/community/contributing-to-documentation/

But the source content seems to contain all the information.
https://github.com/cucumber/docs.cucumber.io/blob/master/content/community/contributing-to-documentation.md

**Comment by mlvandijk** [comment]
Thanks for pointing that out @akshaykamath - I'll have a look

**Comment by mlvandijk** [comment]
Ok, the hack I tried didn't work.
It has to do with Hugo interpreting the language blocks, e.g. `{{% block %}}` and I'm trying to find out if those can be escaped and how. Help welcome ;)

**Comment by xtrasimplicity** [comment]
@mlvandijk, does 
```
{{/* {{% block %}} */}} 
```
work?
https://discourse.gohugo.io/t/a-way-to-mark-plain-text-and-stop-hugo-from-interpreting/1325/2

**Comment by mlvandijk** [comment]
@xtrasimplicity Somewhat, in the sense that it does show up. Except it shows `{{%/* block */%}}` instead of `{{% block %}}`...

**Comment by mlvandijk** [comment]
Problem:
Both languages blocks (e.g. `{{% block "ruby" %}} `and `{{% /block %}}`)
and fenced code blocks (e.g. \```ruby) are not shown in the page when used in the .md file.
They need to be escaped somehow, so Hugo does not interpret them.
