### ISSUE TITLE
Can't scroll to show the full content

### ISSUE THREAD

**Issue by lby1992** [cucumber/docs#212]
![qq 20180804195703](https://user-images.githubusercontent.com/7285065/43676283-c10a5e42-9820-11e8-9ca3-7666c0749f04.png)

Just look at the screenshot above, I'm using Chrome, but the right part didn't show and I can't scroll to them.

**Comment by xtrasimplicity** [comment]
I only have this issue if I zoom into anything greater than 100%. If you press `ctrl` + `0` to reset the zoom setting to 100%, does it show correctly?

Edit: Scratch that, I can't see the final column unless I zoom out much further.

I'll start working on a fix for this, and will submit a PR soon.

**Comment by lby1992** [comment]
@xtrasimplicity ya, I just using the default zooming settings, I think make this content scrollable is a good idea.

**Comment by xtrasimplicity** [comment]
@lby1992 I've just restructured this a little in a new PR. What do you think?
https://5b65b98d792f8926e39ddc7d--cucumber.netlify.com/gherkin/reference/#spoken-languages

**Comment by lby1992** [comment]
@xtrasimplicity Good work, it looks fine now.

**Comment by mlvandijk** [comment]
@xtrasimplicity Thanks for working on this. Tried that last link just now, and am still having the problem (using FF on macOS High Sierra). Tbh I'm not sure the table should be in there at all. It's hard to read and I'm not sure it adds value to have it. @aslakhellesoy added it at some point; I'm not sure why? Maybe it would be better to just remove it, though?

**Comment by xtrasimplicity** [comment]
@mlvandijk I made some more changes which I've mentioned over [here](https://github.com/cucumber/docs.cucumber.io/pull/213#issuecomment-410492270). Personally, I think the __data__ in the table is worth having, but perhaps this particular table format isn't the best way to demonstrate it (hence my changes).
