### ISSUE TITLE
Add docs for gherkin-lint

### ISSUE THREAD

**Issue by jackorp** [cucumber/docs#215]
While inspecting cucumber [issue#450](https://github.com/cucumber/cucumber/issues/450) I found that gherkin-lint seems to miss documentation.

**Comment by mlvandijk** [comment]
And when we have them, link to them from here: https://github.com/cucumber/cucumber/tree/master/gherkin-lint/javascript

**Comment by mlvandijk** [comment]
Sidenote: according to this [README](https://github.com/cucumber/cucumber/blob/master/gherkin-lint/README.md) Gherkin-Lint is not ready for use yet.

**Comment by aslakhellesoy** [comment]
There is no official gherkin-lint implementation. We should remove the docs and the experimental code from master.

**Comment by mlvandijk** [comment]
Created a PR to remove the code here: https://github.com/cucumber/cucumber/pull/452
Closing this issue.
(thanks anyway @jackorp!)
