### ISSUE TITLE
10 minute tutorial, missing code changes for "Using variables and examples" section

### ISSUE THREAD

**Issue by jesusha123** [cucumber/docs#224]
The 10 minute cucumber tutorial needs to describe a generic today_is method that accepts any string.

It should probably be added to "Add another failing test" section, replacing today_is_Friday() method.

The section describes you should add today_is_Friday() method, but when run in maven, the shell block actually shows a generic today_is(String) method instead. This issue also makes the example under "Using variables and examples" section not work.

Example that fixes the issue:
```
    @Given("^today is \"([^\"]*)\"$")
    public void today_is(String today) {
        this.today = today;
    }
```

**Comment by mlvandijk** [comment]
Thank you for pointing that out @chuymax! Would you be up for providing a PR? I'd be happy to offer help if needed, either here on or the Cucumber slack. Unfortunately, I'm away from my computer this week, so cannot do the work myself.
