### ISSUE TITLE
Update 10 min tutorial for Cucumber-jvm v4: Use Cucumber expressions

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#237]
Currently the maven-archetype used in the 10 minute tutorial uses cucumber-jvm v2.3.1. That should be updated to v4 (see: https://github.com/cucumber/cucumber-archetype/issues/2).
Once that is done, the tutorial should be updated for Java to use Cucumber expressions.
Also, the maven-archetype should be updated in the first command.

**Comment by nhojpatrick** [comment]
Just checked here https://docs.cucumber.io/guides/10-minute-tutorial/ and it's using ```-DarchetypeVersion=4.2.6.1 ```

@mlvandijk So think this can be closed.

**Comment by mlvandijk** [comment]
@nhojpatrick Actually, that just means that the precondition to update the tutorial to use Cucumber expressions has been filled.

**Comment by mlvandijk** [comment]
Tutorial is using Cucumber expressions
