### ISSUE TITLE
Tutorial: Test results missing for "Add another failing test" in JavaScript and Ruby

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#238]
In the "10 minute tutorial", under **"Add another failing test"**, there are no test results in JavaScript or Ruby under "When we run this test, it will fail."

They should be added as follows:
{{% block "javascript" %}}
```shell

```
{{% /block %}}

{{% block "ruby" %}}
```shell

```
{{% /block %}}

I'd be happy to accept individual PR's per language.

**Comment by hanneskaeufler** [comment]
I'm on it :)

**Comment by mlvandijk** [comment]
Thanks so much @hanneskaeufler!
