### ISSUE TITLE
Add pitest-cucumber-plugin to related tools

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#245]
Add [pitest-cucumber-plugin](https://github.com/alexvictoor/pitest-cucumber-plugin) to [Related tools](http://docs.cucumber.io/tools/related-tools/) page.
Note: Tools are listed in alphabetical order.

**Comment by TomerPacific** [comment]
@mlvandijk ,
mind if I take this one?

**Comment by mlvandijk** [comment]
Yes please, go ahead!

**Comment by TomerPacific** [comment]
@mlvandijk ,
created a [PR](https://github.com/cucumber/docs.cucumber.io/pull/252)
