### ISSUE TITLE
Document how to run Cucumber from the CLI

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#261]
Running though CLI (how to) - see:
https://groups.google.com/forum/#!topic/cukes/bM_ZHHwks8U
https://www.jeroenreijn.com/2017/10/running-cucumber-from-the-command-line.html

**Comment by TomerPacific** [comment]
@mlvandijk ,
so you would like a section to be added inside the Guides topic explaining how to run Cucumber through the CLI?

**Comment by mlvandijk** [comment]
I think the best place for this would be: http://docs.cucumber.io/cucumber/api/#from-the-command-line.
Note that that is a polyglot page, so any general information should be valid for all (major) programming languages, and things specific to a particular language should be inside language blocks. Please see http://docs.cucumber.io/community/contributing-to-documentation/#polyglot-pages for how to deal with polyglot pages. (Contact me/us in the #docs channel on Slack if you have questions).
And please check that the page renders for each language tab while you are working on it.

**Comment by mlvandijk** [comment]
In addition, add a question to FAQ and link to the section that explains running from the CLI. 
This should be in the section about running Cucumber.

**Comment by annabaker** [comment]
@mlvandijk I was running through this process so I could document it properly, and I'm facing the same issue as: https://stackoverflow.com/questions/31946114/syntax-of-glue-option-for-java-cucumber-cli-cucumber-api-cli-main

From the command line I'm running:
`java -cp "/home/annabaker/.m2/repository/io/cucumber/cucumber-core/4.8.0/cucumber-core-4.8.0.jar:/home/annabaker/.m2/repository/io/cucumber/gherkin/5.1.0/gherkin-5.1.0.jar:/home/annabaker/.m2/repository/io/cucumber/cucumber-expressions/7.0.2/cucumber-expressions-7.0.2.jar:/home/annabaker/.m2/repository/io/cucumber/datatable/1.1.14/datatable-1.1.14.jar:/home/annabaker/.m2/repository/io/cucumber/datatable-dependencies/1.1.14/datatable-dependencies-1.1.14.jar:/home/annabaker/.m2/repository/io/cucumber/cucumber-java/4.8.0/cucumber-java-4.8.0.jar" io.cucumber.core.cli.Main /home/annabaker/Development/git/hellocucumber/src/test/resources/hellocucumber/is_it_friday_yet.feature --glue hellocucumber
`

Here is my glue code:

`package hellocucumber;

import io.cucumber.java.en.Given;

public class StepDefinitions {

    @Given("test data")
    public void test_data() {
        // Write code here that turns the phrase above into concrete actions
       throw new cucumber.api.PendingException();
    }

    @Given("dev data")
    public void dev_data() {
        // Write code here that turns the phrase above into concrete actions
       throw new cucumber.api.PendingException();
    }
}`

(Sorry it's not formatting properly).

I'm using the proper syntax of using the package name (hellocucumber).  Do you spot any issues with the jars I'm using?  Every time I run it, my glue code is ignored and the CLI tells me to implement the missing steps.
