### ISSUE TITLE
Add "Rule" keyword to Gherkin documentation

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#262]
See grammar definition in https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin.berp
Also: https://github.com/cucumber/cucumber/issues/453

Note: should be added when Gherkin 6 is actually used in any/all Cucumber implementations.

**Comment by TomerPacific** [comment]
@mlvandijk ,
I would like to help with this issue. Is it only about adding the word "Rule" when necessary?

**Comment by mlvandijk** [comment]
Thanks @TomerPacific, that would be great. 
Yes, we should add the "Rule" keyword and relevant information about this keyword (see links).

**Comment by TomerPacific** [comment]
Opened a [PR](https://github.com/cucumber/docs.cucumber.io/pull/270)

**Comment by mlvandijk** [comment]
Looks like Gherkin 6 is not implemented yet in Cucumber-jvm:
the [pom.xml](https://github.com/cucumber/cucumber-jvm/blob/master/pom.xml) mentions `<gherkin.version>5.1.0</gherkin.version>` and there's an open [PR](https://github.com/cucumber/cucumber-jvm/pull/1402) to use Gherkin 6.

Cucumber-js [package.json](https://github.com/cucumber/cucumber-js/blob/master/package.json) mentions `"gherkin": "^5.0.0",`

Cucumber-ruby [cucumber.gemspec](https://github.com/cucumber/cucumber-ruby/blob/master/cucumber.gemspec) (if that's the Ruby equivalent of a pom file) does mention `  s.add_dependency 'gherkin', '~> 6.0'`.

So it looks like it's implemented for Ruby, so we should add it to the documentation. However, we should make clear it is not yet implemented in jvm/js, for which there are two options:
1. Put all text regarding `Rule` keyword inside "ruby" text blocks
2. Add a *Note* that Gherkin 6 / `Rule` keyword has not yet been implemented for jvm/js.

Personally I think option 1 would be a safer option (less confusion), but might be a bit more work. What do you think @TomerPacific , @jenisys ?

**Comment by jenisys** [comment]
You can always wait until the last one us on-board. But that is composition problem that will not scale the more implementations you get. 

IMHO a better approach is to document per implementation which Gherkin version it supports. But clarify that with Aslak and/or Matt first. 

Ciao,
Jens

**Comment by mlvandijk** [comment]
Closed by cucumber/common#271
