### ISSUE TITLE
Serenity BDD example does not work

### ISSUE THREAD

**Issue by SiKing** [cucumber/docs#263]
Trying to run through the example for [Serenity BDD](https://docs.cucumber.io/guides/browser-automation/#serenity-bdd), but I cannot figure out where the WebDriver gets initialized.
The documentation only says:

> In this example, the WebDriver interaction is delegated to PageObject subclasses.

But it does not say how, and there is no mention anywhere in the code of `WebDriver`.

Trying to run the example code, I only get:

```
  Scenario: Finding some cheese                    # hellocucumber/find_some_cheese.feature:4
    Given I am on the Google search page           # SearchSteps.i_am_on_the_Google_search_page()
      java.lang.NullPointerException
	at hellocucumber.steps.SearchSteps.i_am_on_the_Google_search_page(SearchSteps.java:18)
	at ✽.I am on the Google search page(hellocucumber/find_some_cheese.feature:5)
```

**Comment by SiKing** [comment]
I figured out the _secret make-it-work switch_: The `class RunCucumberTest` needs to be updated to `@RunWith(CucumberWithSerenity.class)`.

**Comment by aslakhellesoy** [comment]
We should remove the entire SerenityBDD example from our docs. We can link to the SerenityBDD website instead.

**Comment by xtrasimplicity** [comment]
Resolved in https://github.com/cucumber/docs.cucumber.io/pull/264
