### ISSUE TITLE
Missing JavaScript example for "After" hook.

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#273]
There is a missing JavaScript example in the following section: https://docs.cucumber.io/cucumber/api/#after

Currently it says: "TODO: See Ruby or Java example".
This should be replaced by a JavaScript example illustrating the same as the Java/Ruby example.

**Comment by TomerPacific** [comment]
@mlvandijk ,
willing to take this one.

**Comment by mlvandijk** [comment]
That would be great @TomerPacific! Anything you want to pick up, just assign to yourself (see top right) and provide a PR. :)

**Comment by mlvandijk** [comment]
If you're interested, could you also have a look at #214 maybe?

**Comment by TomerPacific** [comment]
@mlvandijk ,
I am looking for the Cucumber Reference inside the content/cucumber directory, but it is not there. Can you point me in the direction of it's location?

**Comment by mlvandijk** [comment]
Yes, it's `api.md` :)

Note that you can always check the URL for location & filename, but I do agree that filenames should match title to make it easier.

**Comment by TomerPacific** [comment]
@mlvandijk ,
I noticed that the [JSON response](http://rmpestano.github.io/cukedoctor/cucumber-js/cucumber-js-documentation.html#_output_json_for_a_feature_with_one_scenario_with_one_undefined_step) does not contain a key - value parameter for the scenario's status, but only for the steps of the scenario.

Would this be what you are looking for:

`let steps = scenario.steps;
for (let i = 0; i < steps.length; i++) {
  if (steps[i].status === "failed") {
    //Add your logic
  }
}`

**Comment by mlvandijk** [comment]
@TomerPacific I'm not sure; I'm not too familiar with JavaScript. From the docs you linked to, I found the following: http://rmpestano.github.io/cukedoctor/cucumber-js/cucumber-js-documentation.html#_check_scenario_statuses so it looks like it is possible to get `sscenario.isFailed()`?

**Comment by mlvandijk** [comment]
You might also want to look at: https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md

**Comment by TomerPacific** [comment]
@mlvandijk ,
I have looked at the links you have posted and I have to ask one more thing. I noticed that in the other languages, the documentation provides code to take a screenshot. Whether it be with a WebDriver or another way, I am not familiar with a way in JS to do so (without an external library). Would you like the JS documentation to include that? [Here](https://html2canvas.hertzen.com/documentation) is a link to a tool to allow taking screenshots.

**Comment by mlvandijk** [comment]
Hi @TomerPacific - It's probably referring to the Selenium WebDriver, which I think should be available also in JavaScript? (for example: https://help.crossbrowsertesting.com/selenium-testing/getting-started/javascript/)

**Comment by TomerPacific** [comment]
Created a [PR](https://github.com/cucumber/docs.cucumber.io/pull/287)
