### ISSUE TITLE
Add API automation tools for JavaScript

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#276]
Add a page on using API automation, similar to the one on [browser automation](https://docs.cucumber.io/guides/browser-automation).

For JVM:
* RestAssured
* other?

What are API automation tools for Ruby, JavaScript?

**Comment by mlvandijk** [comment]
RubyMine van be used to test REST APIs: https://www.jetbrains.com/help/ruby/testing-restful-web-services.html

**Comment by luke-hill** [comment]
I use `curb` in my testing.

Ruby has a default http library called Net/http, but the common ones other people use are things like `faraday`, there's probably I'd say about 6 main ones.

HTTPClient
RestClient
Curb
Faraday
Net/Http
HttpRB

A bigger list is here: https://www.ruby-toolbox.com/categories/http_clients

**Comment by mlvandijk** [comment]
Thnx @luke-hill - do you feel up to making a PR to add them?

**Comment by luke-hill** [comment]
I'll have some free time next weekend. I'll try chip in something then.

**Comment by mlvandijk** [comment]
That would be great @luke-hill!
