### ISSUE TITLE
Add D

### ISSUE THREAD

**Issue by mcandre** [cucumber/docs#283]
An unofficial package exists for using Cucumber with D language projects, [unencumbered](https://github.com/atilaneves/unencumbered). Could we add this to the list of available plugins?

https://docs.cucumber.io/installation/

**Comment by xtrasimplicity** [comment]
Thanks, @mcandre! I'll take a look at this when I get a moment.

Edit: Looks like I'm not going to have time over the next few weeks, so I'll unassign myself.

**Comment by mlvandijk** [comment]
Sure. Would you be willing to create a PR for this, @mcandre ?
