### ISSUE TITLE
Additions to FAQ Page

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#284]
This issue contains several FAQ that we would like to add to the [FAQ page](https://docs.cucumber.io/community/faq/)

There are several in this issue description, separated by lines.
There are several in the comments. 
They will need to be written in a similar format as currently on the FAQ page. Ideally they should answer the question and point to the right place in the docs for more information. 

**== Help wanted ==**
- Partial PR's are fine too! (i.e. adding only one of the questions/topics from this issue to the FAQ page)
- Feel free to add topics / info here that you think should be in the FAQ :)
- Please ask for clarification if anything is unclear. 
==========================

** Use of colons **
From gitter: Jeff Johnson @jeffcjohnson Jan 16 20:45
When writing features, if a newbie like me puts a colon after Given, When or Then, it doesn't complain but doesn't do anything either. It took a while to figure out why my test was being ignored. 
It would be helpful to clarify somewhere in the docs, possibly the Gherkin page. 
UPDATE: In progresss, see https://github.com/cucumber/docs/pull/691

**Comment by mlvandijk** [comment]
~~**Arity mismatch**
`cucumber.runtime.CucumberException: Arity mismatch:` indicates that the step does not provide the arguments needed for the step definition.~~ (DONE in #295)

**Comment by TomerPacific** [comment]
@mlvandijk ,
what exactly would you like added to the FAQ page?

**Comment by mlvandijk** [comment]
@TomerPacific I would like to add additional FAQs to the FAQs page, in a similar style as the ones we have now. Ideally they should answer the question and point to the right place in the docs for more information. You can start with one of these questions mentioned if you are more comfortable with that.  We can collaborate on it through review process if you want (or join us on Slack in the #docs channel if you'd like to discuss more). Feel free to add additional questions + answers you think should be added either here in this issue, or through PR.

**Comment by TomerPacific** [comment]
@mlvandijk , I have created a [PR](https://github.com/cucumber/docs.cucumber.io/pull/295) which is a work in progress so that we can collaborate and identify what else needs to be added to the FAQ. Currently, I have only added the statement regarding arity mismatch.

**Comment by olleolleolle** [comment]
> **Arity mismatch**
> `cucumber.runtime.CucumberException: Arity mismatch:` indicates that the step does not provide the arguments needed for the step definition.

Add this FAQ explanation for Ruby, too.

Hat-tip: @luke-hill 

Update: **DONE**

**Comment by mlvandijk** [comment]
@olleolleolle @luke-hill #295 adds Arity mismatch for all languages (see comments)

**Comment by mlvandijk** [comment]
@TomerPacific Let me know if you want to pick up more of the FAQ?

**Comment by mlvandijk** [comment]
If IntelliJ is not finding your stepdefs, you may need to upgrade IntelliJ / the plugin (especially with Kotlin)

**Comment by mlvandijk** [comment]
When using cucumber-spring add Spring config to **exactly 1** StepDefs class.

**Comment by helenjoscott** [comment]
Hey, I'm not sure if I messed up the git thing this time. I forgot to branch then had to retro fit it, I think.

**Comment by helenjoscott** [comment]
I have a PR open for what I believe are the final two FAQs attached to this ticket. If that's accepted I think we can close this.

**Comment by mlvandijk** [comment]
If the PR re: colons is accepted this issue can be closed

**Comment by mlvandijk** [comment]
Closed by multiple PRs, the last one being #691
