### ISSUE TITLE
What are the different branches for?

### ISSUE THREAD

**Issue by Zearin** [cucumber/docs#29]
When I opened a PR with documentation updates on the main Cucumber repo, I was instructed to rebase my changes on this repo's `sw-reorg` branch.  

Well, I did.  And that’s cool.  Trouble is, I still have no idea what the `sw-` prefixed branches are _for_.  I don’t even know what “sw” means. :)

Can someone explain what the different branches are for?  And how they relate to `master`?

**Comment by plaindocs** [comment]
Hey @Zearin 

That was before we merged the *major* changes into the main branch. `sw` is a prefix for my name, which is a common way of working with many branches.

From now on, all PRs should be made against `master`. If your new branch was against `sw-reorg` I can move it over for you.

**Comment by plaindocs** [comment]
Apologies for any confusion.

**Comment by mlvandijk** [comment]
@Zearin Hope it's clear now. (You can always check the "Current status" in the readme, of ask on Slack if you're not sure). Closing this issue...
