### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by SabotageAndi** [cucumber/docs#304]
There is no license in the repository.
Under which license is the documentation licensed?

**Comment by aslakhellesoy** [comment]
It's MIT - I just added the file.

Thanks!

**Comment by aslakhellesoy** [comment]
On a second thought - MIT is for software, so perhaps we need to pick a different license? Some CC license? Any suggestions?

**Comment by luke-hill** [comment]
I mean technically there still is code here; in both snippet form and some js stuff to generate the website. So the MIT one should still suffice you'd think?

**Comment by mattwynne** [comment]
From https://choosealicense.com/non-software/

> Any open source software license or open license for media is applicable to software documentation.

So I think MIT is fine.
