### ISSUE TITLE
Kotlin duplicated at debugging section

### ISSUE THREAD

**Issue by rafafael03** [cucumber/docs#305]
At [Debugging](https://github.com/cucumber/docs.cucumber.io/blob/master/content/cucumber/debugging.md) doc's section there are duplicated Kotlin tabs.

Probably the first occurrence of the `Kotlin` tab should be the `Javascript` tab.

Bellow is the screenshot from the [page](https://docs.cucumber.io/cucumber/debugging/) of the web site.

[![image](https://user-images.githubusercontent.com/16862690/54318227-5b595b00-45c4-11e9-9d00-509456d40020.png)](https://docs.cucumber.io/cucumber/debugging/)

**Comment by mlvandijk** [comment]
Thanks for pointing that out! Should be fixed now.
