### ISSUE TITLE
More than one Background per Feature with Rule

### ISSUE THREAD

**Issue by sebrose** [cucumber/docs#307]
The documentation for Background says that you can only have one per feature. 

That's not true anymore. For implementations using Gherkin 6 you can also have one per rule, and many rules per feature.

**Comment by mlvandijk** [comment]
Thanks for pointing that out, @sebrose.
It looks like Gherkin 6 has been implemented in Cucumber-Ruby, but not yet in Cucumber-js and Cucumber-jvm. Imho it would be better to update once it's implemented in all 3.

**Comment by mlvandijk** [comment]
Background info: https://github.com/cucumber/cucumber/issues/453

**Comment by mlvandijk** [comment]
Additional info:
* The rule has no impact on how Cucumber runs scenarios
* Rules can have tags
* Rules cannot have Background

**Comment by mlvandijk** [comment]
Closed by cucumber/common#330
