### ISSUE TITLE
Cucumber Pro was renamed to Cucumber Jam

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#309]
Rename in the docs:
* Reporting page
* Other locations?

**Comment by mpkorstanje** [comment]
Maybe we can remove it from the docs? It's kinda weird to have all this open source documentation for a feature that is not available.

**Comment by mlvandijk** [comment]
Valid point. Afaik Jam has it's own docs? We could still link to it though?

**Comment by mpkorstanje** [comment]
Sure. We have this section were we link to other tools right?

**Comment by mlvandijk** [comment]
Yes, we have the Related Tools page: https://docs.cucumber.io/tools/related-tools/
But also the Reporting page, which lists several built-in plugins, Cucumber pro (=> renamed to Cucumber jam), and third-party plugins: https://docs.cucumber.io/cucumber/reporting/

**Comment by mlvandijk** [comment]
We should really check the third-party plugins also for how up to date they are.

**Comment by mlvandijk** [comment]
As discussed with @tooky at Cukenfest the Cucumber Pro section can be removed.

**Comment by mlvandijk** [comment]
Closed by #329
