### ISSUE TITLE
Clarify use of (Maven) profiles on JVM

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#314]
Cucumber profiles are not available on JVM:
https://docs.cucumber.io/cucumber/configuration/#profiles

However it is possible to use [Maven profiles](https://maven.apache.org/guides/introduction/introduction-to-profiles.html) to pass configuration options. 

We should at minimum add this to the page, with a link to the Maven page (and possibly a Gradle page, if Gradle offers the same functionality).
It would be even better if we could provide an example of how that would work.

(Source: https://stackoverflow.com/questions/55341945/how-do-i-use-cucumber-profile-to-dynamically-use-different-environment-hostname)

**Comment by mlvandijk** [comment]
https://stackoverflow.com/questions/59450070/running-multiple-maven-profiles-cucumber-jvm :)

**Comment by anna-engle** [comment]
> https://stackoverflow.com/questions/59450070/running-multiple-maven-profiles-cucumber-jvm :)

Haha, that was me that posted that.  I'll work on my PR to get the fixes in you guys requested.  Sorry, been busy with family for the holidays.
