### ISSUE TITLE
Add running tests with Maven / Surefire to "things that are not Cucumber" page

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#315]
We should clarify how to run tests from Maven/Surefire.
As this is not a Cucumber problem, it should go on the "Things that are not Cucumber problems" page: https://docs.cucumber.io/community/not-cucumber/

We might also want to link there from FAQ.

Source: conversation on Slack:

Bill Hoffmeier [17:34]
I am trying to run selenium cucumber-junit tests from a maven project in Bamboo. The tests run fine in an IDE, but do not run using “mvn clean test” from the command line. Command line simply builds successfully and stops. Should maven be able to run the tests?

aslak [17:51]
@Bill Hoffmeier Can you run regular unit tests from maven?
Make sure the classes end with `*Test.java`

Bill Hoffmeier [17:54]
Thanks @aslak. The classes don’t end with *Test.java. I can try and change the name. Also, as an FYI, the classes are not in src/main; they’re in src/test. Does that make a diff?
That ran the tests but I got a lot of initialization errors that I will work on resolving. Thanks!

aslak [18:03]
@Bill Hoffmeier happy to help. Your problem seems unrelated to Cucumber - it sounds more like you need to figure out how Maven’t surefire plugin works (surefire is the Maven plugin that runs JUnit tests)

**Comment by grasshopper7** [comment]
Links from Maven site for default inclusion\exclusion patterns. Maybe these help.
Surefire - https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html
Failsafe - https://maven.apache.org/surefire/maven-failsafe-plugin/examples/inclusion-exclusion.html

**Comment by mlvandijk** [comment]
@grasshopper7 Would you be up for adding something to the docs?

**Comment by grasshopper7** [comment]
@mlvandijk  Glad to. Let me know which topics and I will give it a shot.

**Comment by mlvandijk** [comment]
@grasshopper7 Any issue that is open and you feel like doing, just assign it to yourself. This one seems like a good candidate? (Sorry for the late reply; I was travelling)

**Comment by mlvandijk** [comment]
In addition: "Maven expects test code to live under src/test/<language>/, by putting RunCukesTest.java under src/main/java you are saying to maven "this is not a test class", try and move RunCukesTest.java to src/test/java." (see: https://github.com/cucumber/cucumber-jvm/issues/1139)

**Comment by grasshopper7** [comment]
@mlvandijk Created PR with Maven help.
