### ISSUE TITLE
Add example of how to capture screenshot on fail

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#320]
Question in https://github.com/cucumber/cucumber-jvm/issues/1504
I'm pretty sure I have Java/Kotlin examples for this.

**Comment by mlvandijk** [comment]
Kotlin example:
```
import cucumber.api.java8.En
import org.openqa.selenium.OutputType
import org.openqa.selenium.TakesScreenshot
import org.openqa.selenium.WebDriver
import org.openqa.selenium.remote.Augmenter
import org.slf4j.Logger
import org.slf4j.LoggerFactory

class ScreenshotOnErrorHook(val webDriver: WebDriver) : En {

    companion object {
        private val logger: Logger = LoggerFactory.getLogger(ScreenshotOnErrorHook::class.java)
    }

    init {
        After { scenario ->
            if (scenario.isFailed) {
                logger.debug("Recording screenshot for failed scenario {}", scenario.name)
                val browser = Augmenter().augment(webDriver) as TakesScreenshot
                val screenshot = browser.getScreenshotAs(OutputType.BYTES)
                scenario.embed(screenshot, "image/png")
            }
        }
    }
}
```

**Comment by mlvandijk** [comment]
Java example:

```
import cucumber.api.Scenario;
import cucumber.api.java8.En;
import cucumber.shared.util.WebDriverManager;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.remote.Augmenter;

public class ScreenshotOnErrorHook implements En {

    public ScreenshotOnErrorHook() {
        After((Scenario scenario) -> {
            if (scenario.isFailed()) {
                TakesScreenshot browser = (TakesScreenshot) new Augmenter().augment(WebDriverManager.getWebDriver());
                final byte[] screenshot = browser.getScreenshotAs(OutputType.BYTES);
                scenario.embed(screenshot, "image/png");
                scenario.write("URL: " + WebDriverManager.getWebDriver().getCurrentUrl());
            }
        });
    }
}
```

**Comment by kavyamurthy1209** [comment]
@mlvandijk : how to use this piece of code in cucumber testng runner? its giving error Can inject only one of <ITestContext, XmlTest, Method, Object[], ITestResult> into a @AfterMethod annotated teardown

My Code is in test runner is:

@AfterMethod(alwaysRun = true)
	public void teardown(Scenario scenario) {
		if (scenario.isFailed()) {
			TakesScreenshot browser = (TakesScreenshot) new Augmenter().augment(driver);
            final byte[] screenshot = browser.getScreenshotAs(OutputType.BYTES);
            scenario.embed(screenshot, "image/png");
            scenario.write("URL: " + driver.getCurrentUrl());
		}
		driver.quit();
	}

**Comment by mlvandijk** [comment]
Don't use it in the runner; add an [After hook](https://docs.cucumber.io/cucumber/api/#after).

**Comment by mlvandijk** [comment]
We already had this question in the [FAQ](https://docs.cucumber.io/community/faq/#taking-a-screenshot-after-failed-steps) with examples in the [After hook](https://docs.cucumber.io/cucumber/api/#after).

Closing this issue.
