### ISSUE TITLE
Add content about declarative steps

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/docs#323]
There should be clear instructions explaining the drawbacks of imperative steps. We should explain this. Some resources for inspiration (copy contents, don't link to them)

* [Declarative steps](https://web.archive.org/web/20100603235246/benmabey.com/2008/05/19/imperative-vs-declarative-scenarios-in-user-stories.html)
* [Pushing the how down](http://www.marcusoft.net/2013/04/PushTheHowDown.html)
* [TODO-subsecond](https://github.com/subsecondtdd/todo-subsecond) - "UI-agnostic scenarios"

**Comment by mlvandijk** [comment]
In addition to: https://docs.cucumber.io/bdd/better-gherkin/

**Comment by jennek** [comment]
I volunteer to write this section. Content-wise, this is familiar territory for me. I have been writing scenarios and implementing step definitions in Cucumber/Ruby for 3 years and in SpecFlow/C# for 3 more years. I totally agree with the insights in the references you mention. Moreover, this theme comes up with every person I have been coaching on BDD. So the time has come for me to put that in writing. 
However, it would be my first contribution to docs.cucumber.io, so I may need some help on how to proceed. I'd rather not propose a fully written text to you straight away, but first propose an outline, then work the examples, and finally polish the text. Please advise.

**Comment by mlvandijk** [comment]
Hi Jennek, thank you for your offer! That would be great :)
The easiest way to discuss would be on Slack in the docs channel. 
If you don't have an account on the Cucumber Slack yet, you can get one [here](https://cucumberbdd-slack-invite.herokuapp.com/).

**Comment by mlvandijk** [comment]
Also, please have a look at what we already have (see the link I provided).
And see https://docs.cucumber.io/community/contributing-to-documentation/ for some background information on how to contribute to the documentation (writing style, tools used, etc).

**Comment by mlvandijk** [comment]
For this issue, I think also/mainly we need to look at examples provided in various parts of the docs, so we consistently show what we mean. This would include changes examples about "go to page x" with something functional a user might be trying to achieve.

**Comment by jennek** [comment]
I agree but let's take this one step at a time. I will first elaborate on the present example, then look at consistency and x-refs -- moreover I need som time to read the docs from the writer's perspective now.

**Comment by mlvandijk** [comment]
Sounds fine. Feel free to start with a small PR, with a small improvement like using a better Gherkin example, or anything else you find while reviewing the current docs.
