### ISSUE TITLE
Import any useful changes from old PRs on http://github.com/cucumber/website

### ISSUE THREAD

**Issue by mattwynne** [cucumber/docs#33]
I'm just cleaning up tickets on http://github.com/cucumber/website and there are four pull requests sitting open on the docs that have been there for a long time:

https://github.com/cucumber/website/pull/8
https://github.com/cucumber/website/pull/4
https://github.com/cucumber/website/pull/3
https://github.com/cucumber/website/pull/1

I'm going to close all of them now, but I suggest someone checks them over to see if anything valuable can be salvaged.

**Comment by plaindocs** [comment]
Thanks! I'll take a look.

**Comment by mlvandijk** [comment]
Related: see #34 for open PR's in https://github.com/cucumber/cucumber

**Comment by mlvandijk** [comment]
Had a quick look already:
* cucumber/website#8 
Contains two topics:
Maven: if info is still up to date, this could be added
Options - are already in jvm.md under "List of options"
* cucumber/website#4
Adds info on Gherkin, Features, Scenarios, Given/When/Then which imho is already covered.
* cucumber/website#3
Contains additional info on Command Line and Ant, which might be relevant
* cucumber/website#1
Adds some "good practices" which imho should be reviewed and added.

**Comment by plaindocs** [comment]
Thanks for that summary @mlvandijk 

I've migrated the relevant part of cucumber/website#8 and have had a look at the rest. I think cucumber/website#4 and cucumber/website#3 could be addressed more systematically if necessary, and unless @aslakhellesoy wants to take a look writing something similar to cucumber/website#1 I'm not sure it is worth merging.
