### ISSUE TITLE
Rename "Things that are not Cucumber problems"

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#338]
We have a page with "Things that are not Cucumber problems" (https://cucumber.io/docs/community/not-cucumber/).
This page lists possible problems with tools that are used with Cucumber, where the problem is not Cucumber itself, but has to do with the other tool used. This explains the current name (the problem is not a Cucumber problem), but doesn't sound very nice. 

Imho we should rename the page to still signify that it's about related tools, but without sounding defensive / offensive about it. Something like "Problems with related tools" / "FAQ about related tools" (Suggestions welcome!)

**Comment by AlokTakshak** [comment]
@mlvandijk I will update it and raise a PR.

**Comment by mlvandijk** [comment]
Thank would be great @AlokTakshak!

**Comment by AlokTakshak** [comment]
> Thank would be great @AlokTakshak!

I have raised the PR , if you want we can discuss on title more

**Comment by mlvandijk** [comment]
Fixed by #354

**Comment by mlvandijk** [comment]
Thanks @AlokTakshak - this title is fine; it's better than the previous one. Thanks for taking the time to raise the PR!
