### ISSUE TITLE
java-gradle example project link is 404.

### ISSUE THREAD

**Issue by grasshopper7** [cucumber/docs#342]
The java-gradle example project link in the page https://cucumber.io/docs/tools/java/#gradle is dead. It refers to this https://github.com/cucumber/cucumber-jvm/tree/master/examples/java-gradle which has been removed since 4.0.0. This link existed till version 3.0.2 - https://github.com/cucumber/cucumber-jvm/tree/v3.0.2/examples/java-gradle.

**Comment by mlvandijk** [comment]
Hmm, thanks for pointing that out. Was the java-gradle example removed by design @mpkorstanje ? (If so, the link should be removed imho)

**Comment by mpkorstanje** [comment]
Yes. It was a pain to maintain as part of `cucumber-jvm`. I think the https://github.com/cucumber/cucumber-java-skeleton might be a good replacement. Though ideally with Gradle you'd use https://github.com/tsundberg/gradle-cucumber-runner instead of the JUnit runner.

**Comment by mlvandijk** [comment]
Should we link to https://github.com/tsundberg/gradle-cucumber-runner instead, @mpkorstanje ?

**Comment by mpkorstanje** [comment]
Wouldn't hurt I guess.

**Comment by mlvandijk** [comment]
Fixed by #355
