### ISSUE TITLE
Aslak’s testable-architecture-devlin-2017 ppt link in testable-architecture.md is Invalid

### ISSUE THREAD

**Issue by missley** [cucumber/docs#373]
Aslak’s testable-architecture-devlin-2017 ppt link in testable-architecture.md is Invalid

**Comment by olleolleolle** [comment]
Would this https://speakerdeck.com/aslakhellesoy/testable-architecture-devlin-2017 do?

**Comment by olleolleolle** [comment]
Would you like to offer a PR with a change to make the documentation usable?

**Comment by missley** [comment]
> Would this https://speakerdeck.com/aslakhellesoy/testable-architecture-devlin-2017 do?

Yes, is this URL working ?i can't access this URL, maybe my network has some problem?

**Comment by olleolleolle** [comment]
It works for me, it's a presentation to page through by click/tap on the right side of the presentation slide.

**Comment by mlvandijk** [comment]
Current link works for me (both slides and talk). 
Could you provide more information about what's wrong @missley ?

**Comment by mlvandijk** [comment]
Closing this issue. Feel free to comment with more information and it can be reopened
