### ISSUE TITLE
Use Cucumber Expressions rather than Regular Expressions

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/docs#375]
#### Background

The 10 minute tutorial still uses Regular Expressions. Other pages possibly too.

#### Solution

We should use Cucumber Expressions everywhere (except when we explain regular expressions explicitly).

**Comment by Riggs333** [comment]
I'd like to pick this one up in the context of our local Hackergarten event today.

**Comment by aslakhellesoy** [comment]
That would be much appreciated @Riggs333! Have a fun Hackergarten!
