### ISSUE TITLE
More inclusive language in the docs

### ISSUE THREAD

**Issue by carolstran** [cucumber/docs#389]
:wave: I noticed that there are many instances of the word "simple" (or similar variations) in your documentation. Unfortunately, words like this can make people feel frustrated and isolated while reading (myself included, hence the issue) - especially if they are facing issues. 

If it's alright with your team, I'd like to take a shot at updating the content to make it more inclusive by removing instances of "simple", "easy", etc. 😊 

Also if you're interested or want more information on this topic, I'd highly recommend watching Jim Fisher's [Don't Say Simply](https://www.youtube.com/watch?v=gsT2BBWBVmM) talk from Write the Docs Prague 2018 ✍️ 🤓 

Thank you for the work you do and please let me know if you need more details!

**Comment by luke-hill** [comment]
Definitely agree with this. I actually altered a couple of those recently myself in some docker information. And it's likely I'm guilty of writing it in a few other places.

I'll happily review and merge any PR like this, as it's something I'm quite keen on

**Comment by carolstran** [comment]
Awesome! I'm on it 🚀

**Comment by mlvandijk** [comment]
Yes please @carolstran! I was not aware we were doing that and we obviously intend to help, not frustrate. Multiple PR's would also be welcome for this, if you'd like to take it one page/section at a time. 
If you have any question, please join us on [Slack](https://cucumberbdd-slack-invite.herokuapp.com/) in the #docs channel.

**Comment by mlvandijk** [comment]
Thanks so much for pointing that out!
