### ISSUE TITLE
Rename tagged hooks to conditional hooks

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/docs#392]
> Mark Jordan 12:08 PM
> Hello, I'm experimenting with tagged hooks and I'm noticing my before hook with no tags is running after the tagged before hook? Is that normal? If I'm tagging before Hooks, do I need to tag them all and not have a general non tagged before hook?

> mpkorstanje 12:23 PM
> Okay so:
> 1. Tagged hooks a is a misnomer. They're more like conditional hooks. The hook is executed when the tag expression in the hook matches the tags on the scenario. So a hook tagged with `@cucumber` or `@gherkin` will run on Scenarios tagged wither either `@cucumber` or `@gherkin`.
> 2. Hooks without a tag use the empty tag expression which matches all tags.
> 3. Hook order comes from the order in which hooks are defined in the class file. But I do not believe this order is defined by the JVM and should not be relied up on too much. Use  the order property to control the order in which hooks are executed.

Renaming this in the docs would perhaps resolve some of these issues. Adding an example would help too.

**Comment by mlvandijk** [comment]
Great idea!
