### ISSUE TITLE
Implement / improve search

### ISSUE THREAD

**Issue by plaindocs** [cucumber/docs#40]
We need some kind of decent search:

Two obvious options are:

* [Algolia free doc search](https://community.algolia.com/docsearch/)
* [Lunr](https://lunrjs.com/guides/getting_started.html) 

I suggest we implement both as long as it isn't too time consuming, and contrast and compare.

**Comment by plaindocs** [comment]
https://www.npmjs.com/package/hugo-lunr

**Comment by aslakhellesoy** [comment]
The site now has basic Lunr search

**Comment by olleolleolle** [comment]
Could one say that we’re waiting for launch to have Algolia? Or can it be configured already?

**Comment by plaindocs** [comment]
We could easily configure Algolia with a the URL, compare it to the Lunr and then reconfigure before launch. Or just go with Lunr.

**Comment by aslakhellesoy** [comment]
We've got some basic lunr search now. Try it out: https://cucumber.netlify.com/documentation/

**Comment by mlvandijk** [comment]
Having the search is great.
Getting an overview of pages that might have what you are looking for is also nice.
However, when you go to one of the suggested pages, the list of suggested and the search term (whatever you typed into the search box) disappear. I think it might be nice if those could be kept, until the search box is explicitly cleared (in case the page you choose from the suggestions isn't what you were looking for; you don't want to have to search again (and again, and again) for the same thing...
Also, is there any way to get info on what people are searching for (and whether they find it), as that might provide feedback regarding missing docs / what is unclear? (this would be a nice to have / enhancement)
It might be a good idea to keep the search term / search results unless explicitly cleared in case

**Comment by aslakhellesoy** [comment]
Yep highlighting the search terms is on the todo list. Let’s keep this open until that’s done.

**Comment by mlvandijk** [comment]
- [ ] Highlighing (see above)
- [ ] Improve subtitles, based on `description` in the frontmatter. Make them consistent with subtitles shown in the menu
- [ ] Add possibility to clear search box (i.e. by clicking an `x` and/or `esc`)

**Comment by mlvandijk** [comment]
Discussed on Cukenfest Open Space: switch to Algolia

**Comment by mlvandijk** [comment]
We seem to be using Algolia now. Closing this issue (also due to lack of activity)
