### ISSUE TITLE
Junit runner class not detected in certain circumstances.

### ISSUE THREAD

**Issue by nocon** [cucumber/docs#415]
**Is your feature request related to a problem? Please describe.**
Today, I've spent a good few hours trying to force maven to run the cucumber tests via junit runner. The issue turned out to be relatively simple: surefire (since version 2.22) will not detect  junit 4 based tests if junit-vintage-engine dependency is not included. No errors, no clues, absolute nightmare to figure out. Including junit-vintage-engine solves the issue, of course. 

**Describe the solution you'd like**
Ideally? A Maven warning message on the test step if the project includes a cucumber junit runner, but not junit-vintage-engine. I don't know if it's possible (and what would be involved), but it would be a lifesaver. 

I'm not overly familiar with junit / cucumber / surefire, so if this is not solvable within this project, I'd be happy to report it elsewhere - please let me know where, though.

**Describe alternatives you've considered**
On top of the above, if the cucumber-jvm documentation mentioned junit-vintage-engine as indirect dependency, that would probably help in most cases. Possibly, here: https://cucumber.io/docs/cucumber/api/#junit

If I missed an easier way to make cucumber-jvm + junit + surefire combo work, please let me know!

**Comment by mpkorstanje** [comment]
> I'm not overly familiar with junit / cucumber / surefire, so if this is not solvable within this project, I'd be happy to report it elsewhere - please let me know where, though.

Thanks for point this out. Unfortunately we can't solve this within Cucumber. It depends entirely on Maven/Surefire and JUnit. But if you want you can add a note to docs yourself! 

Something along the line of "If you are using JUnit 5 you'll have to use JUnit vintage. See link to the JUnit5 docs". should be sufficient. 

The junit docs are here:

https://github.com/cucumber/docs.cucumber.io/blob/master/content/docs/cucumber/api.md#junit
