### ISSUE TITLE
Change links under "Docs" menu on https://cucumber.io/docs

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#433]
Since adding the Cucumber docs to the SmartBear site, there is a menu option "Docs" that offers several links to the actual docs:
1. The arrow > goes to https://cucumber.io/docs/cucumber/ - which is a good place to start
2. Installation
3. Gherkin Syntax
4. API Docs -> goes to API automation tools that are not Cucumber
5. 3rd Party Tools -> goes to tools that for the most part are not cucumber.

I think nr 4 and 5 should not be part of this high level menu.
Instead I would like to include:
* Guides and/or 10 minute tutorial
* Community and/or FAQ
Alternatively, "Cucumber" could be one of the links and the arrow > could go to docs landing page.

If we have data on which pages people look for that would also be helpful.

**Comment by anna-engle** [comment]
I searched in IntelliJ, and found 100+ matches for where this HTML should be changed.  In addition, all of the .html files are read-only -- is there a single location where we can update this?

Another opinion:  I feel the FAQ should be moved out of the "Community" section and into its own section, with two children: Cucumber FAQ and FAQ about related tools.  It is easier to access by end-users this way.  My $0.02.

**Comment by mlvandijk** [comment]
I agree with you second point. Feel free to create a PR for that, would very much appreciate it.

I'm not actually sure where this menu is created tbh; it might be in the SmartBear website and we might be unable to change it. html is likely generated somehow (@aslakhellesoy will know more about the technical setup of how the frontend is created, I just do content ;) )

**Comment by helenjoscott** [comment]
Hi @mlvandijk, are you thinking something like this? Would you want the API or 3rd Party links to be anywhere in this menu?

<img width="508" alt="Screenshot 2020-10-14 at 09 14 27" src="https://user-images.githubusercontent.com/13313561/95961969-b507b400-0dfd-11eb-99dc-bdc82d550f57.png">

**Comment by mlvandijk** [comment]
@helenjoscott Yes, something like that. I don't think API and 3rd party links should be in this menu. Note I'm not sure that these links can be changed in this project; they might have to be changed in the SmartBear website.

Also I agree with @annabaker that FAQ should be taken out of Community. But for restructuring please have a look at https://github.com/cucumber/docs.cucumber.io/issues/474

**Comment by helenjoscott** [comment]
Well I mocked it up and I seem to have managed to change them... I think. I can do a PR and someone with some knowledge (which isn't me) can take a look?

**Comment by mlvandijk** [comment]
Closed by #528
