### ISSUE TITLE
Java 10 Minute Tutorial says Stepdefs instead of StepDefinitions

### ISSUE THREAD

**Issue by hayden-mumm** [cucumber/docs#448]
The page I'm referring to is here: https://cucumber.io/docs/guides/10-minute-tutorial/

Underneath "See scenario reported as undefined" right at the bottom it says to copy the files in to Stepdefs.java . When I created the project no file called that was created, it was called StepDefinitions.java .

It also says that in the code snippet under "See scenario reported as failing" and "Using variables and examples"

Not sure if this is a version difference or what.

I am using Eclipse if that makes a difference.

**Comment by luke-hill** [comment]
If you feel comfortable about raising a PR to correct the behaviour we would happily review and merge it.

**Comment by hayden-mumm** [comment]
Unfortunately I do not have time at the moment.
