### ISSUE TITLE
Cucumber multiple stepdef not working on spring boot application

### ISSUE THREAD

**Issue by sunilkcs** [cucumber/docs#457]
Unable to use multiple stepdefinition and autowire the spring boot app components for my tests. Tried almost all the samples got from Google.  Getting "Please ensure only one glue class configures the spring context". Cucumber documentation also very poor in this. Not explaining this issue properly anywhere.

**Comment by mlvandijk** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

That said, for more information about using Cucumber-spring, please see [cucumber-jvm/spring](https://github.com/cucumber/cucumber-jvm/tree/master/spring).

Also, try to read the error message and do what it suggests: Only annotate *one* glue (or Step definitions) class with a Spring context.

If you need more help, please join the support channels.
If you solve your problem, we would love a pull request that explains this properly.

**Comment by sunilkcs** [comment]
Again , the project you mentioned is old style xml based configs not annotation based. All i wanted was a very simple spring boot app with at least 2 feature files, 2 step definitions  and both the definitions must contain autowired application components to run various tests with out throwing any  spring context, or these glue related errors.  People copy pastes codes from here n there on their blog pages. But nothing worked for me. I think i need to go back to normal Junit/TestNG based approach.  Closing this as per your suggestion. Thank you.
