### ISSUE TITLE
[proposal] Add recommended media

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#48]
Not just current links to blog posts, but also:
* links to Cucumber books(?)
* links to Cukenfest videos.
* links to podcasts (directly to an overview of podcasts, not just from the cucumber blogs)

**Comment by plaindocs** [comment]
A quick glance at the Cukenfest sites showed no videos. Do you know if there are any?

**Comment by aslakhellesoy** [comment]
@theo-england - I think @plaindocs is right. I couldn't find links to videos from 2017 anywhere on http://cukenfest.cucumber.io/. In particular, the "Watch Videos" link on http://cukenfest.cucumber.io/2017 doesn't show any.

Can you help with this @theo-england ?

**Comment by mattwynne** [comment]
Yes, it looks like something has gone wrong with the page on squarespace.

For now, you can find the videos here: https://www.youtube.com/playlist?list=PLrQMyTCtW0DZD6YYTaJpFJpwfyKeuvWIV

**Comment by mlvandijk** [comment]
Added the idea as I saw some blogs mentioning the videos:
* https://cucumber.io/blog/2017/08/21/cukeup-au-2016-videos
* https://cucumber.io/blog/2017/08/07/cukeup-london-2017-videos
We can add the link(s) to http://cukenfest.cucumber.io/ when they're up there?

**Comment by mlvandijk** [comment]
In general it would be nice to have a list of the things mentioned in the Slack channel, especially if they're not already in the blogs etc list.

**Comment by theo-england** [comment]
@mlvandijk - I've fixed the link on the 2017 page and added another header.
http://cukenfest.cucumber.io/

Did you want to see recommended media somewhere specifically on docs pages? We realise that sometimes our popular content and podcasts can get lost in the noise on our blog. We hope to make it more accessible soon.

**Comment by mlvandijk** [comment]
@theo-england Awesome, thanks!

Context (why I raised this issue): Right now if I'm looking for a particular podcast I search though the blog posts on the site, or when looking for a video I have to look through the Slack channel(s). It's great content that is somewhat hard to find ;)
That's why I was thinking a page listing resources (incl books & videos) might be nice. It could be a place where we list (Cucumber/BDD) books, (links to) videos and podcast, etc. Searchable by type (book/video/audio) might also be handy. 
It could also be a page on the website rather than in the docs.

**Comment by mlvandijk** [comment]
In addition, when people are asking for a place to find more information on Cucumber, we point them to The Cucumber Book. Wouldn't it be nice to have a direct link to buy it somewhere?

**Comment by mlvandijk** [comment]
Started branch 'media' to include a few links to videos / podcasts that are not cukenfest / cucumber podcasts. There may be more that I'm not aware of (@theo-england)? We could also include the cukenfest videos / cucumber podcasts here, or provide a link. Let me know what you think.

**Comment by mlvandijk** [comment]
I've noticed a Talks page on the website; is that were the videos should be (as opposed to in the docs)?. Unfortunately I've not yet been able to find out where they're added.

**Comment by mattwynne** [comment]
I think the website is the right place for this rather than the docs site. @mlvandijk did you know the website itself is quite hackable?

**Comment by mlvandijk** [comment]
Agreed! I'll close this issue. @mattwynne The website uses Ruby and I don't, so haven't been able to find it just yet.

**Comment by mattwynne** [comment]
@mlvandijk aha! Yeah that makes sense. If you'd like to learn I'd be happy to pair with you to get you set up. Most of the work on the website is HTML/Markdown templates.
