### ISSUE TITLE
documentation for attaching infos to scenario in cucumber-jvm

### ISSUE THREAD

**Issue by boris779** [cucumber/docs#486]
The documentation for attaching text/screenshot to the scenario is a bit outdated

https://cucumber.io/docs/guides/browser-automation/?sbsearch=attach#browser-automation-tools-for-jvm
In Cucumber 5.7.0 the emed is deprecated, and if I got it right in v6 it is removed and replaced with attach.

**Comment by luke-hill** [comment]
That is correct @boris779 - Currently we're trying to get the API standardised for each language cucumber is written in. Once we've got them all standardised, things should be easier to look at.

For now we just try to keep the docs reasonably up to date with what works currently, and as mentioned, feel free to submit some tweaks if you think you can improve on them. We welcome contributions to the docs from everybody!
