### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#52]
Would it be helpful to add an FAQ page? I've noticed some questions have come up several times just on Slack alone.
Examples:
* cannot find jvm v2.0 => group id has changed
* message that steps are not defined even though they are, due to glue path not being configured correctly

**Comment by aslakhellesoy** [comment]
Yes!!! I've felt guilty about bot having one for years so starting one would be great. Best way to handle recurring questions on ML.

**Comment by aslakhellesoy** [comment]
* cucumber and excel (don't, explain why)

**Comment by mlvandijk** [comment]
* skipping steps (don't, explain why)

**Comment by mlvandijk** [comment]
* issues with runners / how to run

**Comment by plaindocs** [comment]
If at all possible, I've a strong preference for first finding the right place for that info to live, and then linking to it in the form of an FAQ.

**Comment by mlvandijk** [comment]
@plaindocs Yes, I agree. However, sometimes people don't find the documentation; it might be helpful to have a list of common problems...

**Comment by mlvandijk** [comment]
Additional FAQ (which should -also- be clarified in the docs):
- Getting 'undefined steps' because glue is not found (where does it look for the glue by default, how to set where to find the glue) - so many StackOverflow questions...
- Running though CLI (how to) - see: 
* https://groups.google.com/forum/#!topic/cukes/bM_ZHHwks8U
* https://www.jeroenreijn.com/2017/10/running-cucumber-from-the-command-line.html
=> Note there is a separate issue on adding this information (#261). It should be added and then linked from the FAQ to that section.
* Taking a screenshot on fail (& explain taking screenshot every step is an antipattern)

**Comment by mlvandijk** [comment]
Input for "Cucumber can't find my glue" (from @brasmusson on Slack): Cucumber-JVM will search for step definitions in the packages you told it to look in. Either you put your step definitions files in the default package where Cucumber-JVM searches, that is the package (or sub-packages) of the runner class - in your case the package `com.Create_Customer_API`, or you tell Cucumber-JVM explicitly which packages (which includes the sub-packages) to search with the `glue = {"<package>", "<package>", "<etc>"}` in the `@CucumberOptions` annotation - in your case `glue = {"Create_Customer_API"}`

**Comment by mlvandijk** [comment]
How to share state between steps: in JVM, use DI (needs more documentation anyway).  Link to list of supported DI framework (currently here: https://cucumber.io/docs/reference/java-di). If your project already uses any of these framework (or you are familiar with one of them), it's easiest to use that. If you don't already use one, Picocontainer is the most light weight version you can use.
There's a little information in the Cucumber for Java book.

**Comment by mlvandijk** [comment]
ANSI color thingy: https://github.com/cucumber/cucumber-java-skeleton/issues/18

**Comment by mlvandijk** [comment]
Details in scenarios: http://dhemery.com/pdf/writing_maintainable_automated_acceptance_tests.pdf

**Comment by mlvandijk** [comment]
From @mattwynne : 
"I’m teaching a class today, and I’m getting questions where I’m struggling to find docs to point people to with the answers:

1) how does Cucumber-JVM go about searching for glue code, by default?
2) what are the configuration parameters you can pass to your `RunCukesTest` JUnit bridge? e.g. glue, plugin etc.
3) how do you use java 8 lambdas for defining steps"

From @brasmusson 
"
1) Cucumber-JVM use the package of the runner class as default (when using the command line runner, there is not default)
2) See https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/api/CucumberOptions.java
3) See https://github.com/cucumber/cucumber-jvm/blob/master/examples/java8-calculator/src/test/java/cucumber/examples/java/calculator/RpnCalculatorStepdefs.java
"

**Comment by mlvandijk** [comment]
Clarify Cucumber expressions vs Regex, see: https://github.com/cucumber/cucumber/issues/515

**Comment by mlvandijk** [comment]
https://foreach.atlassian.net/wiki/spaces/CWB/blog/2015/07/02/9404422/Quick-fix+for+issues+with+IntelliJ+14.1.3+

Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/transaction/TransactionDefinition.

The cause is incorrect detection of the Glue property, for some reason the package cucumber.api.spring is added incorrectly.

only cucumber.api.spring is added to glue
"regular" glue not added by default, need to add manually.

**Comment by mlvandijk** [comment]
Added a FAQ page, with most but not all FAQ mentioned here. Maybe create a new issue with pending FAQ?

**Comment by mlvandijk** [comment]
Questions about dynamic data (don't; tests should be deterministic).
