### ISSUE TITLE
Missing built-in junit reporter or wrong documentation?

### ISSUE THREAD

**Issue by saurabh-deep** [cucumber/docs#585]
The reporting documentation [here](https://cucumber.io/docs/cucumber/reporting/#built-in-reporter-plugins) mentions that there is a built-in junit reporter. But when I use `--format junit`, it doesn't work and complains that module 'junit' is missing.

I tried to look into the error and found that method `getConstructorByType` in [builder.ts](https://github.com/cucumber/cucumber-js/blob/master/src/formatter/builder.ts) doesn' have any mention of `junit`. So, is it a case of wrong documentation?

We have been using a JSON to JUNIT converter previously, which works great for us. But we are now upgrading to cucumber-js 7.0 which warns us that `The built-in JSON formatter is deprecated and will be removed in the next major release`. To be able to use JUNIT converter, the output needs to be in JSON. We don't want to use json-formatter since it has prebuilt executables, which doesn't work for us.

Can someone please guide me on how to get the JUNIT output from cucumber-js v7.x without using the depcrecated JSON format?

Much appreciated!

**Comment by saurabh-deep** [comment]
@davidjgoss - Appreciate the super quick response! And looking forward to the junit reporter implementation for cucumber-js!

**Comment by saurabh-deep** [comment]
@davidjgoss - Is there a way to suppress the following warning that is displayed when using JSON reporter with v7.0?

```
The built-in JSON formatter is deprecated and will be removed in the next major release. Where you need a structured data representation of your test run, it's best to use the `message` formatter. For legacy tools that depend on the deprecated JSON format, a standalone formatter is available (see https://github.com/cucumber/cucumber/tree/master/json-formatter).
```

**Comment by aslakhellesoy** [comment]
I think the only way to suppress the message is to stop using the `json` formatter. What do you need it for @saurabh-deep ?

**Comment by saurabh-deep** [comment]
@aslakhellesoy - In fact we need the JUNIT output, which is missing from cucumber-js. AFAIK, only option seems to be to first get the JSON output and then convert it to JUNIT. @davidjgoss also mentioned above that it is fine to use JSON formatter till the time JUNIT formatter is not available natively in cucumber-js.

Is there any other way to get the JUNIT output from cucumber-js v7.x without triggering the JSON format deprecation warning?

**Comment by davidjgoss** [comment]
@saurabh-deep from the community there is  https://www.npmjs.com/package/cucumber-junit-formatter which has no dependency on the JSON output. It doesn’t support v7.0.0 yet but the author is working on it per https://github.com/mvtm-dn/cucumber-junit-formatter/issues/10.
