### ISSUE TITLE
Fix outdated documentation on tagging (java)

### ISSUE THREAD

**Issue by camohub** [cucumber/docs#599]
I have a test runner which is based on tags. [Documentation](https://cucumber.io/docs/cucumber/api/) says the signature has to be like:
```
package runners;

import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;
import org.junit.runner.RunWith;

@RunWith(Cucumber.class)
@CucumberOptions(
    features = "src/test/features/",
    glue = {"steps", "hooks"},
    tags = {"@admin", "@user"},
    plugin = {"pretty"}
)
public class FastRunner
{

}
```
But this tags signature throws me an error: **java: annotation value not of an allowable type**

What is wrong with that? Thanks a lot for help.

**Comment by mpkorstanje** [comment]
@luke-hill the documentation on docs.cucumber.io still references the old syntax. I'm moving this item there.
