### ISSUE TITLE
Update Docs for language correction in gherkin i-18 table

### ISSUE THREAD

**Issue by sohamghoshjobprofiles** [cucumber/docs#630]
Once the [issue #1595 on the common repo](https://github.com/cucumber/common/issues/1595) is fixed, the docs will have to be updated to reflect this change

**Comment by luke-hill** [comment]
@sohamghoshjobprofiles is this something you wanted to tackle, or should I close this off?

**Comment by sohamghoshjobprofiles** [comment]
@luke-hill 
The docs look updated here 

> https://cucumber.io/docs/gherkin/languages/

Am I looking at the right place?
