### ISSUE TITLE
Add a note in the introduction of the 10 minutes tutorial to inform that it prerequisites basic development knowledge

### ISSUE THREAD

**Issue by BoWunder** [cucumber/docs#647]
The "10 min tutorials" on https://docs.cucumber.io/docs/guides/10-minute-tutorial/ are frustrating to use. It presume much from the readers when it suddenly swift between Command-promt windows and Ruby etc. between steps. It presumes that that the reader would understand "Gemfile", let alone how to use them.

This may be enough information for someone who already know Ruby and Cucumber from the get-go (which would make a tutorial unnecessary by definition), but when you're a new user who only know "enough" to get around, but not to get into every crevasse, then it's a frustrating experience. It feels at times as if you get talk down to for them not knowing what the tutorial, by definition, should have been able to tell me in the first place.

**Describe the solution you'd like**
Images/Screenshots that shows when and where you are at any given point. To show where you as a reader are when the tutorial-text jump around in the menu. To show which window/command window etc. you're currently in at any given moment.

Describe alternatives you've considered
Bulleting, that clearly states the How and Where to do the how.

Additional context
(See image for reference).
That is just an example of the "installing process". There are plenty more in the text, but for this example, you can see the attatched screenshot for reference.

1: It start with "We’ll start by creating a new directory and an empty Ruby project." (In the same project or as two separate entities? Is the directory specific to the project or a new default? Should the directory be called something specific (like Gemfile) or is that optional?)

Then it goes down to "Create a Gemfile with the following content:" - As a new user and as a ready, the question on ones mind is "Where?" In the directory? In the project file itself? In a new place? Should the Gemfile be given a specific filetype? (like Gemfile.rb?) Should the reader just write-in the versions as they are presented on the sire (Screenshot), or should they use the command-promt to find the right versions? (cucumber -version or other similar?). Does it matter?

Thirdly, we get to "Install Cucumber and prepare the file structure:" - Again, is that in Ruby or in command promt? Is the reader still in the Gemfile? Should this be added at the start of a new [File].feature?

I hope that this shows the issue I personally have had as a new user. The tutorial jump left and right with little explanation or consideration to anyone who supposedly not already possesses enough knowledge to make a tutorial void in the first place. It is called a "10 minutes tutorial", but personally, I have yet to reach the end of the tutorial. This is frustrating, partly due to the aforementioned "jumps", but also when you do manage to follow the tutorial, since when you come across an issue that halt one process, then you don't know why. This is especially an issue when it comes to writing an issue-report or asking for help, because you cannot be sure that you installed things right in the first place.

<img width="684" alt="text ex" src="https://user-images.githubusercontent.com/86303765/123971315-38802a00-d9ba-11eb-8c5e-0ece0b201caf.PNG">

**Comment by aurelien-reeves** [comment]
> 
> 
> I think we should state at the top of the tutorial that some prior knowledge is required:
> 
>     * Basic understanding of the Ruby programming language
> 
>     * Basic understanding of the Bundler tool and `Gemfile`
> 
>     * Some experience using a terminal
> 
>     * Some experience using a text editor
> 
> 
> It's beyond the scope of the Cucumber docs to teach readers these things, but we can link to some resources we recommend.

So I think we accepted to add those prerequisites in the 10 minutes tutorial
And same kind for all languages (javascript, java)

**Comment by TomerPacific** [comment]
Hey @aurelien-reeves , I would like to help out with this. Have you agreed upon the structure of the note you would like to add in the documentation per language?

**Comment by aurelien-reeves** [comment]
Hi @TomerPacific 

I am glad that you want to help! :D

We did not discuss further that topic. Feel free to submit a PR, it will be a good way to iterate on it based on reviews and feedbacks! :)

Do you need some help to get started?

**Comment by TomerPacific** [comment]
@aurelien-reeves  sorry for the late reply.
I have contributed in the past, but I need to sync my repositories first.
I'll draft something up and link to the PR here once it is opened.

**Comment by TomerPacific** [comment]
@aurelien-reeves , having some trouble checking my changes locally via Docker.
Receiving this:
`$ ./docker_shell.sh
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
`
Following the suggestion, I ran:
` winpty ./docker_shell.sh
winpty: error: cannot start 'C:/PATH_TO_REPO/docs/docker_shell.sh': %1 is not a valid Win32 application. (error 0xc1)
`
I tried researching online to find a solution, but couldn't find anything substantial. I don't have any experience with Docker. 

Any chance that you know how I can overcome this issue? I am using a Windows 10 Home edition machine (64 bit) and by the message in the terminal I am assuming there is a problem with that fact.

**Comment by aurelien-reeves** [comment]
It appears our scripts are not compatible with Windows.

If you have docker installed, try executing the following command directly (from the root directory of the project):

    docker run -p 1313:1313 -e "CI=false" --volume .:/app -it cucumber/hugo:1e65815e43ac30f7d52080356fd0893a

An alternative could be to use a virtual machine with linux. Or [WSL](https://docs.microsoft.com/en-us/windows/wsl/), but not sure it can be installed on Windows Home edition.

Also, to fix the current issue, I guess you could just edit the markdown files and submit your PR. We will then be able to check the result with the CI.
