### ISSUE TITLE
Fix or remove outdated link to cucumber/datatable

### ISSUE THREAD

**Issue by shahabhm** [cucumber/docs#672]
**Describe the bug**
in the [api docs](https://cucumber.io/docs/cucumber/api/), at the end of 'Data Table' subsection of 'Step Arguments' section, there is a line saying: For more information, see [cucumber/datatable](https://github.com/cucumber/common/tree/main/datatable). but the link does not exist.

**Comment by aurelien-reeves** [comment]
Thanks for the report @shahabhm
