### ISSUE TITLE
The readability of the code examples is extremely bad based on select color schema

### ISSUE THREAD

**Issue by khmarbaise** [cucumber/docs#692]
**Describe the bug**
I'm trying to read the documentation in particular the code examples etc. like on this page:
Just picked up two examples. (Also see the screen shots)
* https://cucumber.io/docs/guides/overview/
* https://cucumber.io/docs/guides/10-minute-tutorial/

The problem is that the color schema for the code example has white on a grey which is not really readable..

The developer tools of Brave (for example9) are showing the accessibility and contrast is not the best.

![Screenshot 2021-10-31 at 13 03 59](https://user-images.githubusercontent.com/42484/139582202-85e06db4-e667-4c9b-aaf6-ee57bc8cb6a0.png)
))

**Expected behavior**
It would be great to change the color schema for the code example to make them better readable.

**Screenshots**
* ![Screenshot 2021-10-31 at 12 23 42](https://user-images.githubusercontent.com/42484/139581486-82ec0076-39a8-4bf3-9525-bedb9ce42a84.png)

* ![Screenshot 2021-10-31 at 12 45 36](https://user-images.githubusercontent.com/42484/139581519-e0100636-43b7-47ac-ad85-ba54a6b24bc2.png)

**Desktop (please complete the following information):**
I've tested on the following browsers:
* Chrome(Version 95.0.4638.54)
* Safari(Version 14.1.1 (14611.2.7.1.6)), 
* Brave(Version 1.30.87 Chromium: 94.0.4606.71), 
* Firefox(93.0 (64-bit

**Comment by mlvandijk** [comment]
As discussed in Slack, this might be related to recent changes pushed to the website.

**Comment by aslakhellesoy** [comment]
See https://github.com/cucumber/docs/pull/689#issuecomment-955698425 - I have reverted the change for now and the code is now legible again.

Could you please have a look at this @declark?

**Comment by khmarbaise** [comment]
Hi to all, thanks for that. That is really good readable now. Thanks.
