### ISSUE TITLE
Netlify preview broken

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/docs#715]
Look like renaming the relative urls to absolute urls faaae66f05d85e01b4d2b68c82511daff464cc07 broke the netlify preview. Clicking the landing page sends me to the live doc site rather then the preview.

See: https://github.com/cucumber/docs/pull/714

@mattwynne @declark :point_up:

**Comment by mpkorstanje** [comment]
It also looks like the docs are available on `https://cucumber.io/docs/` so it looks like renaming the urls wasn't needed?

**Comment by mpkorstanje** [comment]
Ah. Right. https://docs.cucumber.io/ doesn't redirect  to https://cucumber.io/docs/ but mirrors it. Dunno what the intention here is but it seems a little shoddy.

**Comment by mattwynne** [comment]
Appears to be fixed, e.g. https://deploy-preview-723--cucumber.netlify.app/

Thanks @declark
