### ISSUE TITLE
Is it allowed to have more than one Feature in a file?

### ISSUE THREAD

**Issue by mbelsky** [cucumber/docs#735]
Hi cucumber team,

It looks like a `.feature` file can contain only one `Feature` keyword, however I haven't found any proof of it [here](https://cucumber.io/docs/gherkin/reference/).

Could you please share the answer with me and maybe we can also mention it on Gherkin Reference page.

**Comment by aslakhellesoy** [comment]
Yes, you can only have a single `Feature` in a `.feature` file.
