### ISSUE TITLE
Hugo partial layout named warn.html for warning messages use wrong combination CSS classes

### ISSUE THREAD

**Issue by 10xtechie** [cucumber/docs#760]
### 👓 What did you see?

a **_Hugo_** partial layout - named `warn.html` i.e `themes/cucumber-hugo/layouts/shortcodes/warn.html` -  for warning messages use wrong combination of CSS classes. It uses `message is-danger` css classes instead of `message is-warning`. As a result, when JS tab is clicked on https://cucumber.io/docs/cucumber/step-definitions page, warning message is highlighted in red colour; see screenshot below. Note the usage of `warn` step-definitions.md at line number [93](https://github.com/cucumber/docs/pull/193)

![unexpected-look](https://user-images.githubusercontent.com/102477169/174466077-ed02f0f6-3956-4378-96f7-66a43bfe0634.png)

### ✅ What did you expect to see?

![expected-look](https://user-images.githubusercontent.com/102477169/174466034-5b6f7ed9-5f2a-4e84-bd90-4a1638f426c6.png)

### 🔬 How could we reproduce it?

1. Install '...' version '...'
2. Create a file called '....'
3. Run command '....'
4. See error '....'

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by aurelien-reeves** [comment]
Thanks for your PRs and everything.
But actually the theme used with cucumber docs is not the hugo one, but the cucumber-sb one.

So to actually deploy your changes, we have to port them to the cucumber-sb theme too

It is in progress in #764

**Comment by aurelien-reeves** [comment]
Done in #764
