### ISSUE TITLE
There is no Hugo partial layout - named danger.html in themes/cucumber-hugo/layouts/shortcodes/ folder like warn.html

### ISSUE THREAD

**Issue by 10xtechie** [cucumber/docs#761]
### 🤔 What's the problem you've observed?

There is no Hugo partial layout - named `danger.html in themes/cucumber-hugo/layouts/shortcodes/ ` folder like warn.html. 
However, a CSS class for danger - named` is-danger `is there in the `cucumber.css` file. It will be useful to show messages with **_danger/critical_** severity. 

### ✨ Do you have a proposal for making it better?
Creating a `danger.html in themes/cucumber-hugo/layouts/shortcodes/ ` folder. 

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by aurelien-reeves** [comment]
Fixed in #763
