### ISSUE TITLE
Reconfigure CloudFront for cucumber.io

### ISSUE THREAD

**Issue by v4dkou** [cucumber/docs#766]
I cannot access the documentation without VPN, all pages under https://cucumber.io respond with a 403 ERROR.
"The Amazon CloudFront distribution is configured to block access from your country."

My IP: 212.164.46.34

The solution to this would be to update the configuration for CloudFront

**Comment by aurelien-reeves** [comment]
Duplicate of https://github.com/cucumber/cucumber-js/issues/1983

**Comment by v4dkou** [comment]
Even if this is a duplicate, I disagree with closing both issues until the problem is resolved.

In the meantime, I've spun up a mirror documentation webpage so as to continue using docs without having to circumvent the faulty CloudFront configuration
https://cucumber-io.netlify.app/
