### ISSUE TITLE
Docs website formatting is broken

### ISSUE THREAD

**Issue by jeeeem** [cucumber/docs#817]
### 👓 What did you see?

Nothing. The docs for tags https://cucumber.io/docs/cucumber/api/?lang=java#tags is not visible

### ✅ What did you expect to see?

Docs for tags should be seen when accessing https://cucumber.io/docs/cucumber/api/?lang=java#tags

**Comment by mpkorstanje** [comment]
They got renamed to "Conditional Hooks" in https://github.com/cucumber/docs/commit/325d2232b2e409aa2001e06db91746f5ec272bb0. The subject matter didn't really change. Are you missing anything specific?

**Comment by jeeeem** [comment]
I just access the URL before  last dec-2022. The commit you have given is last 2019.  The detail I'm looking for is the info about how the tags can use with multiple scenarios.

As you see in the pic when I try clicking `tags` hyperlink, it navigates to nothing as I far I can remember it, the **cucumber reference** have docu for tags usage.

![image](https://user-images.githubusercontent.com/51053482/210303774-e685cb07-e952-4b8a-a0de-08a21e98de2c.png)

Update: I check the repo docs. 

https://github.com/cucumber/docs/blob/main/content/docs/gherkin/reference.md

In **feature**,
![image](https://user-images.githubusercontent.com/51053482/210304203-345252a0-31c7-4299-b166-18f562372958.png)

This is what I'm trying to find the tags info, but trying to access this I guess, it has been removed?

![image](https://user-images.githubusercontent.com/51053482/210304258-e9fbb82b-d61d-49a7-b677-771a3f93e4cc.png)

Maybe I'm not remembering it right but I'm sure that's where I got my notes about tagging.

**Comment by mpkorstanje** [comment]
What you're looking for can be found here, https://github.com/cucumber/docs/blob/main/content/docs/cucumber/api.md#tags

not sure why it doesn't show up in the docs.

**Comment by mpkorstanje** [comment]
Looks like the conditional has gone unbalanced just after the Around. But I'm really not seeing which one.

https://github.com/cucumber/docs/blob/main/content/docs/cucumber/api.md#around

![image](https://user-images.githubusercontent.com/6946919/210422154-8155fa4f-08c6-4d74-a836-a6b26e0c4270.png)

@olleolleolle I think this is partially due to the surprise Hugo upgrade https://github.com/cucumber/docs/issues/813.

**Comment by mpkorstanje** [comment]
Seeing how the "WebDriver" is no longer inline with the rest of the sentence it looks like everything gets turned into paragrapths.  I'm not sure which syntax we use for the short codes but if it's go template like we might have to use `{{-` and `-}}` to trim whitespace and maybe put it all on one line.

https://github.com/cucumber/docs/blob/main/themes/cucumber-hugo/layouts/shortcodes/text.html

https://pkg.go.dev/text/template

**Comment by jeeeem** [comment]
> What you're looking for can be found here, https://github.com/cucumber/docs/blob/main/content/docs/cucumber/api.md#tags
> 
> not sure why it doesn't show up in the docs.

Thanks I see it now.

**Comment by mlvandijk** [comment]
Had a quick look and see a few more issues with the page. Nothing after the header "Install plugin" is shown (in any language tab), and the page above that header doesn't look great either, for example: 1) some code blocks are not properly formatted, 2) there are new lines where there shouldn't be. I'll try to have a look later as to why, and how to fix it.

**Comment by mpkorstanje** [comment]
If you're trying to reproduce this locally, be sure to use `hugo v0.85.0`. This is the current version of Huge used by Netlify.

**Comment by mlvandijk** [comment]
https://gohugo.io/content-management/shortcodes/

**Comment by mlvandijk** [comment]
**1. {{text}} blocks should be rendered inline** (not start on new line)
* For some reason {{text}} blocks are not / no longer rendered inline, while they should (block is defined as `<div>`, text is defined as `<span>`. 

**2. Code blocks immediately at the start of a {{text}} or {{block}} section should be formatted as code**
* For some reason code blocks (starting with three backticks) that are right at the beginning of a {{text}} or {{block}} without any preceding text are not / no longer rendered properly. (i.e. the text with backticks is shown, instead of a code block)

To see if this has been resolved, revert one of my workarounds in #827 where I add text or a newline between the start of the {{block}} and the start of the code block.

For example:
```
{{% block "kotlin" %}}

```kotlin
```

to 


```
{{% block "kotlin" %}}
```kotlin
```

**Comment by mlvandijk** [comment]
Reported by Benjamin in Slack: "Hello, I noticed a bug in the Cucumber documentation (not with the text itself but with the functionality.
On the Java reporting page https://cucumber.io/docs/cucumber/reporting/?lang=java, the sections “Custom formatters” and  “Third-party plugins” are not visible. These are only there on the “JS” page https://cucumber.io/docs/cucumber/reporting/?lang=javascript
Since my own “Third party plugin” is a Java/Maven plugin, this is of personal interest "

**Comment by mlvandijk** [comment]
**3. Links at end of sentence not shown correctly.**
For some reason markdown links are not rendered correctly when followed by a period at the end of a sentence. Or when followed directly by a closing shortcode. (adding a workaround to remove the period / add new line before closing shortcode; and sometimes that workaround doesn't work either)

For example, at the end of these pages:
https://cucumber.io/docs/cucumber/api/?lang=javascript
For more information on how to configure options, have a look at the [cucumber-js docs on GitHub](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md)

<img width="1280" alt="Screenshot 2023-01-20 at 09 37 24" src="https://user-images.githubusercontent.com/20927578/213652151-4b14f071-96bf-4936-9a6c-097f1c412ef8.png">

https://cucumber.io/docs/cucumber/api/?lang=ruby
You can also define common command-line options in a [`cucumber.yml`](/docs/cucumber/configuration) file.

Also, in the middle of this page: https://cucumber.io/docs/cucumber/api/?lang=java

<img width="1241" alt="Screenshot 2023-01-20 at 09 45 31" src="https://user-images.githubusercontent.com/20927578/213653480-2e4392b8-3a67-40bb-a3b7-4b489cc42751.png">

**Comment by mlvandijk** [comment]
**4. Markdown formatting should be rendered correctly, eg ** should be bold**
Using ** to make text bold is sometimes rendered correctly, and sometimes not. I've not been able to figure out why.

**Comment by mlvandijk** [comment]
Managed to partially fix the issue(s), mostly with workarounds. Looks like front end stuff from here, which is outside of my area of interest. Maybe @mattwynne and/or @aslakhellesoy can have a look?

**Comment by mpkorstanje** [comment]
Based on what I saw in #813 I'm guessing that we went from Hugo < 0.55 to Hugo >= 0.85. And there appear to have been some changes to how templates work. E.g:

https://gohugo.io/content-management/shortcodes/#shortcodes-with-markdown

This way too much work right now.

@mattwynne it also appears that we now have a `cucumber-hugo` and `cucumber-smartbear` template. Perhaps you can pull in some of the folks who did the original migration.

**Comment by mpkorstanje** [comment]
This might be a better option:

https://docs.netlify.com/integrations/frameworks/hugo/#hugo-version

**Comment by mattwynne** [comment]
ugh, OK leave it with me

**Comment by mlvandijk** [comment]
**5. Lists are not rendered correctly**
I've "fixed" this in #827 by adding a newline before the start of the list. Revert this workaround to see if it has been fixed.

For example:
```
{{% block "java,kotlin" %}}

* `message`
* `progress`
* `pretty`
* `rerun`
* `junit`
* `testng`
```

to 

```
{{% block "java,kotlin" %}}
* `message`
* `progress`
* `pretty`
* `rerun`
* `junit`
* `testng`
```



Also see
https://cucumber.io/docs/guides/10-minute-tutorial/?lang=javascript
List after "Please be aware that this tutorial assumes that you have a:" is not rendered correctly on all pages. It looks fine on Java page, but on JS page: 
<img width="678" alt="Screenshot 2023-01-20 at 09 42 04" src="https://user-images.githubusercontent.com/20927578/213653038-569e8213-da1f-4e78-9364-5fa837974872.png">

**Comment by mlvandijk** [comment]
**6. Inline "code" formatting is not always rendered correctly.**


https://cucumber.io/docs/cucumber/api/?lang=java
For example: 
"Step hooks are invoked before and after a step. The hooks have 'invoke around' semantics, meaning that if a `BeforeStep` hook is executed the `AfterStep` hooks will also be executed regardless of the result of the step. If a step did not pass, the following step and its hooks will be skipped."

<img width="1349" alt="Screenshot 2023-01-20 at 09 37 09" src="https://user-images.githubusercontent.com/20927578/213652010-0aaa65c4-046b-4218-84e1-d5b2473550e2.png">

"**BeforeStep**" and "**AfterStep**" are between backticks and should be rendered as red text, like "**Before**"and "**After** are later on the page: 

"Hooks can be conditionally selected for execution based on the tags of the scenario. To run a particular hook only for certain scenarios, you can associate a `Before` or `After` hook with a [tag expression](https://cucumber.io/docs/cucumber/api/?lang=java#tag-expressions)."

<img width="1349" alt="Screenshot 2023-01-20 at 09 37 02" src="https://user-images.githubusercontent.com/20927578/213652015-7b00fd6b-386f-41f6-9d0c-e8451a5f97c7.png">

**Comment by declark** [comment]
@mlvandijk thanks for flagging these items and providing examples. I'll get the SmartBear Web Devs to take look as soon as possible.

**Comment by mpkorstanje** [comment]
In light of the [recent developments around SmartBear and Cucumber](https://mattwynne.net/new-beginning) I don't expect this will be fixed soon.

**Comment by declark** [comment]
@mpkorstanje we will continue to support the Cucumber Open community. Some resources should be freeing up shortly to get these items resolved.

**Comment by declark** [comment]
@mlvandijk and @mpkorstanje - I've made a change in the build configuration for the docs that seems to have resolved many of the issues mentioned above. The Dockerfile has Hugo configured at version 0.40 where as the version in production was 0.85.0.

Please confirm that this adjustment fixed the above issues.

**Comment by mpkorstanje** [comment]
Looks good! Cheers!
