### ISSUE TITLE
Python Cucumber: Is there a Behave replacement?

### ISSUE THREAD

**Issue by fiona-s37** [cucumber/docs#876]
In the Cucumber docs, [Behave](https://cucumber.io/docs/installation/python/) is listed as the semi-official library of record. However, it has been unmaintained for several years. Is there a Behave replacement out there, or an official library in the works?

**Comment by blaisep** [comment]
It's ... complicated.
[pytest-bdd.readthedocs.io/en/latest/](https://pytest-bdd.readthedocs.io/en/latest/)
tends to be more current, but it requires pytest.

Behave is actually more active than it appears, it's just that jenisys hasn't cut a release in a long time.
There's some controversy on that ...
Anyway, Behave is not intended to be the reference implementation for cucumber on Python, it just happens to be the most pervasive. So Jens is not obligated to be in synch with the latest features.
No one is.

The cucumber Slack has a channel called committers-python and that might be the place to bring this up.

**Comment by fiona-s37** [comment]
I really appreciate the comment, Blaise. We'll look into the active community :)
