### ISSUE TITLE
Json Cucumber mergeFeaturesWithRetest

### ISSUE THREAD

**Issue by Djonathan-Kaiper-Carguero** [cucumber/docs#896]
In Cucumber there is a function called "mergeFeaturesWithRetest" that merges two or more Json and generates an HTML.

Would you like to know how to create a consolidated JSON?

**Comment by mlvandijk** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
