### ISSUE TITLE
Document/script Coala

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/docs#9]
I noticed the `/.coafile` and discovered it's for a linting tool called [Coala](https://coala.io/), which I'm unfamiliar with. We should:

- [ ] Document what it is and how to use it in `CONTRIBUTING.md`
- [ ] Make sure it runs as part of CI

**Comment by plaindocs** [comment]
Yeah, I used it as a once off to clean up the markdown. Will document also.

**Comment by mlvandijk** [comment]
Can this issue be closed?

**Comment by jenisys** [comment]
@aslakhellesoy 
Just a comment: Coala is a static analysis "integration tool", meaning it can run other static code analysis tool for various programming languages. Some tools also provide auto-fixing feature that rewrites the code to fix a problem (if feasible / possible), similar to what you may be used in Eclipse.

**Comment by plaindocs** [comment]
I used Coala to clean up the source markdown initially. I'm going to delete the config file and close this.
