### ISSUE TITLE
How to enable test data externalization (through Excel/JSON etc.) using Cucumber Java and TestNG?

### ISSUE THREAD

**Issue by Zarmeena** [cucumber/docs#900]
Currently I am using Scenario Outline to execute the scenario for multiple data iterations . Also, TestNG's data provider annotation is used as follows to fetch the scenarios for execution:
 @DataProvider (parallel = true)
    //@DataProvider
    public Object[][] scenarios(){
        return runner.provideScenarios();
    }

How differently can I use @DataProvider to read data from excel and feed it to the scripts for multiple executions? 
Appreciate guidance on this !!

**Comment by luke-hill** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.
