### ISSUE TITLE
Missing Watirmelon Links Breaking Netlify Checks

### ISSUE THREAD

**Issue by mxygem** [cucumber/docs#92]
https://app.netlify.com/sites/cucumber/deploys/5a3cc0c88198767e07da8ff5

data from @mlvandijk in #89 :

The following links are failing on HTMLProoofer:
9:23:02 AM: * External link http://watirmelon.com/2011/01/21/my-simple-cucumber-watir-page-object-pattern-framework failed: 404 No error

External link http://watirmelon.com/2011/01/23/reducing-step-explosion-by-decoupling-cucumber-steps-from-your-gui failed: 404 No error
9:23:02 AM: * External link http://watirmelon.com/2011/05/18/specification-by-example-a-love-story failed: 404 No error
9:23:02 AM: * External link http://watirmelon.com/2011/07/04/the-elements-of-cucumber-style failed: 404 No error
9:23:02 AM: * External link http://watirmelon.com/2011/07/04/use-cucumber-feature-folders-for-functional-organization-tags-for-non-functional-classification failed: 404 No error
9:23:02 AM: * External link http://watirmelon.com/2011/08/04/capturing-screenshots-in-watir-webdriver-cucumber failed: 404 No error
9:23:02 AM: * External link http://watirmelon.com/2011/08/07/keeping-the-browser-open-when-youre-writing-a-cucumber-test failed: 404 No error
9:23:02 AM: * External link http://watirmelon.com/2011/08/08/making-your-cucumber-step-definitions-more-readable-with-rspec-binary-matchers failed: 404 No error
9:23:02 AM: * External link http://watirmelon.com/2011/08/10/capturing-page-performance-times-with-my-watirmeloncucumber-framework failed: 404 No error
9:23:02 AM: * External link http://watirmelon.com/2011/08/29/running-your-watir-webdriver-tests-in-the-cloud-for-free failed: 404 No error
I've checked one of them and am getting:"Oops! That page can’t be found."
So these links need to be updated/removed(?)

**Comment by olleolleolle** [comment]
Perhaps we can point at archive.org links in their Wayback Machine?

**Comment by mlvandijk** [comment]
@jaysonesmith @olleolleolle If these links point to information that is still relevant, then please see about updating them. Otherwise, just delete them. (I'm not familiar with Watir so can't say really)

**Comment by aslakhellesoy** [comment]
We should delete broken links
