### ISSUE TITLE
Automate gherkin-i18n-table based on json of gherkin repo

### ISSUE THREAD

**Issue by WikiRik** [cucumber/docs#936]
### 🤔 What's the problem you're trying to solve?

When looking at the docs you can find [a table of the translations](https://cucumber.io/docs/gherkin/languages/), but it's not up to date. It can be updated manually but I think it would be nicer if it is in sync with the gherkin repo itself.

### ✨ What's your proposed solution?

It would be nice if the [gherkin-i18n-table](https://github.com/cucumber/docs/blob/main/layouts/shortcodes/gherkin-i18n-table.html) would be generated based on the [json in the gherkin repo](https://github.com/cucumber/gherkin/blob/main/gherkin-languages.json) which to my understanding is the most up to date version.

### ⛏ Have you considered any alternatives or workarounds?

As mentioned above; updating can be done manually. We can also look at the json instead of the docs.

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by mlvandijk** [comment]
Would you be up for contributing such a change @WikiRik ?

**Comment by WikiRik** [comment]
Apparently it's already possible, but it's a manual process now. See https://github.com/cucumber/docs/blob/main/layouts/shortcodes/README.md
Would you be okay with me adding a GitHub action that runs every week or so to check if there are any updates and if so, commit and open a PR?

In the meantime I've opened https://github.com/cucumber/docs/pull/939 so at least we're up to date now

**Comment by WikiRik** [comment]
@mlvandijk did you get a chance to look at my idea of adding a GitHub Action to check for updates regularly?

**Comment by mpkorstanje** [comment]
@WikiRik if you're still interested building it, I would be interested a PR that automates this with a Github action. Do bear in mind that because this repository is relatively open, it will have to work without secrets.

**Comment by WikiRik** [comment]
@mpkorstanje That's understandable, I'll take a look at it and see what I can get working
