### ISSUE TITLE
Question for Background with Feature and Rule

### ISSUE THREAD

**Issue by lsaudon** [cucumber/docs#943]
### Is this valid?
```gherkin
Feature: Feature name
    Background: Background name one
        Given whatever
    Scenario: Scenario name one
        Given something
    Rule: Rule name
        Background: Background name two
            Given whatever
        Scenario: Scenario name two
            Given something
```
###  And this?

The documentation say `A Background is placed before the first Scenario/Example, at the same level of indentation`.
I can't make this?

```gherkin
Feature: Feature name
    Background: Background name one
        Given whatever
    Rule: Rule name
        Background: Background name two
            Given whatever
        Scenario: Scenario name two
            Given something
```

**Comment by luke-hill** [comment]
Yes you can make that.

Please take questions to the support forum/slack though

**Comment by lsaudon** [comment]
Then the documentation is incomplete.

**Comment by luke-hill** [comment]
@lsaudon - please feel free to use the edit functionality on the docs website there should be a link on each page allowing you to edit them or pull the repo and make manual edits should you so wish. Any support you are able to give is greatly appreciated.

**Comment by lsaudon** [comment]
That's why I asked the question.
